// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module OFM_STORE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_dma_O_TDATA,
        output_dma_O_TVALID,
        output_dma_O_TREADY,
        output_dma_O_TLAST,
        input_dma_B_TDATA,
        input_dma_B_TVALID,
        input_dma_B_TREADY,
        input_dma_B_TLAST,
        OFM_0_V_address0,
        OFM_0_V_ce0,
        OFM_0_V_q0,
        OFM_0_V_address1,
        OFM_0_V_ce1,
        OFM_0_V_we1,
        OFM_0_V_d1,
        OFM_1_V_address0,
        OFM_1_V_ce0,
        OFM_1_V_q0,
        OFM_1_V_address1,
        OFM_1_V_ce1,
        OFM_1_V_we1,
        OFM_1_V_d1,
        OFM_2_V_address0,
        OFM_2_V_ce0,
        OFM_2_V_q0,
        OFM_2_V_address1,
        OFM_2_V_ce1,
        OFM_2_V_we1,
        OFM_2_V_d1,
        OFM_3_V_address0,
        OFM_3_V_ce0,
        OFM_3_V_q0,
        OFM_3_V_address1,
        OFM_3_V_ce1,
        OFM_3_V_we1,
        OFM_3_V_d1,
        OFM_4_V_address0,
        OFM_4_V_ce0,
        OFM_4_V_q0,
        OFM_4_V_address1,
        OFM_4_V_ce1,
        OFM_4_V_we1,
        OFM_4_V_d1,
        OFM_5_V_address0,
        OFM_5_V_ce0,
        OFM_5_V_q0,
        OFM_5_V_address1,
        OFM_5_V_ce1,
        OFM_5_V_we1,
        OFM_5_V_d1,
        OFM_6_V_address0,
        OFM_6_V_ce0,
        OFM_6_V_q0,
        OFM_6_V_address1,
        OFM_6_V_ce1,
        OFM_6_V_we1,
        OFM_6_V_d1,
        OFM_7_V_address0,
        OFM_7_V_ce0,
        OFM_7_V_q0,
        OFM_7_V_address1,
        OFM_7_V_ce1,
        OFM_7_V_we1,
        OFM_7_V_d1,
        BIAS_V_address0,
        BIAS_V_ce0,
        BIAS_V_we0,
        BIAS_V_d0,
        BIAS_V_q0,
        custom_Tr,
        custom_Tc
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_pp1_stage0 = 7'd8;
parameter    ap_ST_fsm_state6 = 7'd16;
parameter    ap_ST_fsm_state7 = 7'd32;
parameter    ap_ST_fsm_state8 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [55:0] output_dma_O_TDATA;
output   output_dma_O_TVALID;
input   output_dma_O_TREADY;
output   output_dma_O_TLAST;
input  [31:0] input_dma_B_TDATA;
input   input_dma_B_TVALID;
output   input_dma_B_TREADY;
input   input_dma_B_TLAST;
output  [7:0] OFM_0_V_address0;
output   OFM_0_V_ce0;
input  [25:0] OFM_0_V_q0;
output  [7:0] OFM_0_V_address1;
output   OFM_0_V_ce1;
output   OFM_0_V_we1;
output  [25:0] OFM_0_V_d1;
output  [7:0] OFM_1_V_address0;
output   OFM_1_V_ce0;
input  [25:0] OFM_1_V_q0;
output  [7:0] OFM_1_V_address1;
output   OFM_1_V_ce1;
output   OFM_1_V_we1;
output  [25:0] OFM_1_V_d1;
output  [7:0] OFM_2_V_address0;
output   OFM_2_V_ce0;
input  [25:0] OFM_2_V_q0;
output  [7:0] OFM_2_V_address1;
output   OFM_2_V_ce1;
output   OFM_2_V_we1;
output  [25:0] OFM_2_V_d1;
output  [7:0] OFM_3_V_address0;
output   OFM_3_V_ce0;
input  [25:0] OFM_3_V_q0;
output  [7:0] OFM_3_V_address1;
output   OFM_3_V_ce1;
output   OFM_3_V_we1;
output  [25:0] OFM_3_V_d1;
output  [7:0] OFM_4_V_address0;
output   OFM_4_V_ce0;
input  [25:0] OFM_4_V_q0;
output  [7:0] OFM_4_V_address1;
output   OFM_4_V_ce1;
output   OFM_4_V_we1;
output  [25:0] OFM_4_V_d1;
output  [7:0] OFM_5_V_address0;
output   OFM_5_V_ce0;
input  [25:0] OFM_5_V_q0;
output  [7:0] OFM_5_V_address1;
output   OFM_5_V_ce1;
output   OFM_5_V_we1;
output  [25:0] OFM_5_V_d1;
output  [7:0] OFM_6_V_address0;
output   OFM_6_V_ce0;
input  [25:0] OFM_6_V_q0;
output  [7:0] OFM_6_V_address1;
output   OFM_6_V_ce1;
output   OFM_6_V_we1;
output  [25:0] OFM_6_V_d1;
output  [7:0] OFM_7_V_address0;
output   OFM_7_V_ce0;
input  [25:0] OFM_7_V_q0;
output  [7:0] OFM_7_V_address1;
output   OFM_7_V_ce1;
output   OFM_7_V_we1;
output  [25:0] OFM_7_V_d1;
output  [2:0] BIAS_V_address0;
output   BIAS_V_ce0;
output   BIAS_V_we0;
output  [25:0] BIAS_V_d0;
input  [25:0] BIAS_V_q0;
input  [31:0] custom_Tr;
input  [31:0] custom_Tc;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_dma_O_TVALID;
reg input_dma_B_TREADY;
reg OFM_0_V_ce0;
reg OFM_0_V_ce1;
reg OFM_0_V_we1;
reg OFM_1_V_ce0;
reg OFM_1_V_ce1;
reg OFM_1_V_we1;
reg OFM_2_V_ce0;
reg OFM_2_V_ce1;
reg OFM_2_V_we1;
reg OFM_3_V_ce0;
reg OFM_3_V_ce1;
reg OFM_3_V_we1;
reg OFM_4_V_ce0;
reg OFM_4_V_ce1;
reg OFM_4_V_we1;
reg OFM_5_V_ce0;
reg OFM_5_V_ce1;
reg OFM_5_V_we1;
reg OFM_6_V_ce0;
reg OFM_6_V_ce1;
reg OFM_6_V_we1;
reg OFM_7_V_ce0;
reg OFM_7_V_ce1;
reg OFM_7_V_we1;
reg[2:0] BIAS_V_address0;
reg BIAS_V_ce0;
reg BIAS_V_we0;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_dma_O_TDATA_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] exitcond_flatten1_reg_1181;
reg    input_dma_B_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond1_fu_467_p2;
reg   [65:0] indvar_flatten1_reg_379;
reg   [2:0] i1_reg_390;
reg   [63:0] indvar_flatten_reg_401;
reg   [30:0] j_reg_412;
reg   [30:0] k_reg_423;
wire   [3:0] i_1_fu_473_p2;
reg    ap_block_state2;
wire   [31:0] tmp_fu_493_p2;
reg   [31:0] tmp_reg_1149;
wire    ap_CS_fsm_state3;
wire   [31:0] tmp_s_fu_498_p2;
reg   [31:0] tmp_s_reg_1155;
wire   [63:0] bound_fu_509_p2;
reg   [63:0] bound_reg_1160;
wire   [65:0] tmp_3_fu_515_p3;
reg   [65:0] tmp_3_reg_1166;
wire   [0:0] notrhs_mid_fu_523_p2;
reg   [0:0] notrhs_mid_reg_1171;
wire   [0:0] tmp_11_mid_fu_529_p2;
reg   [0:0] tmp_11_mid_reg_1176;
wire   [0:0] exitcond_flatten1_fu_552_p2;
wire    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state5_pp1_stage0_iter1;
reg    ap_sig_ioackin_output_dma_O_TREADY;
reg    ap_block_state5_io;
reg    ap_block_pp1_stage0_11001;
wire   [65:0] indvar_flatten_next1_fu_557_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [2:0] tmp_4_mid2_v_fu_590_p3;
reg   [2:0] tmp_4_mid2_v_reg_1190;
wire   [0:0] sel_tmp_mid2_fu_635_p3;
reg   [0:0] sel_tmp_mid2_reg_1195;
wire   [0:0] sel_tmp6_mid2_fu_649_p3;
reg   [0:0] sel_tmp6_mid2_reg_1201;
wire   [0:0] sel_tmp8_mid2_fu_669_p3;
reg   [0:0] sel_tmp8_mid2_reg_1207;
wire   [30:0] j_mid2_fu_750_p3;
wire   [0:0] tmp_last_fu_769_p2;
reg   [0:0] tmp_last_reg_1218;
wire   [30:0] k_2_fu_790_p2;
wire   [63:0] indvar_flatten_next_fu_802_p3;
wire   [63:0] indvar_flatten_next2_fu_1055_p2;
wire    ap_CS_fsm_state7;
wire   [30:0] tmp_7_mid2_v_fu_1075_p3;
wire   [0:0] exitcond_flatten2_fu_1050_p2;
wire   [30:0] k_1_fu_1102_p2;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
reg   [3:0] i_reg_368;
reg   [2:0] ap_phi_mux_i1_phi_fu_394_p4;
reg   [63:0] indvar_flatten2_reg_434;
wire    ap_CS_fsm_state6;
reg   [30:0] j2_reg_445;
reg   [30:0] k3_reg_456;
wire   [63:0] tmp_2_fu_488_p1;
wire  signed [63:0] tmp_14_cast_fu_779_p1;
wire   [63:0] tmp_4_mid2_fu_598_p1;
wire  signed [63:0] tmp_21_cast_fu_1091_p1;
wire    ap_block_pp1_stage0_01001;
reg    ap_reg_ioackin_output_dma_O_TREADY;
wire   [31:0] bound_fu_509_p0;
wire   [31:0] bound_fu_509_p1;
wire   [31:0] tmp_4_fu_534_p1;
wire   [31:0] k_cast_fu_543_p1;
wire   [0:0] exitcond_flatten_fu_569_p2;
wire   [2:0] i_2_fu_563_p2;
wire   [0:0] notlhs_mid1_fu_603_p2;
wire   [0:0] notlhs_fu_609_p2;
wire   [0:0] sel_tmp_mid1_fu_623_p2;
wire   [0:0] sel_tmp_fu_629_p2;
wire   [0:0] sel_tmp3_fu_643_p2;
wire   [0:0] sel_tmp8_mid1_fu_657_p2;
wire   [0:0] sel_tmp4_fu_663_p2;
wire   [0:0] notrhs_fu_538_p2;
wire   [0:0] tmp_6_fu_547_p2;
wire   [30:0] j_mid_fu_574_p3;
wire   [0:0] tmp_11_mid1_fu_684_p3;
wire   [30:0] k_mid_fu_582_p3;
wire   [30:0] j_2_fu_691_p2;
wire   [8:0] tmp_11_fu_709_p1;
wire   [8:0] tmp_13_fu_713_p3;
wire   [8:0] tmp_22_fu_721_p1;
wire   [31:0] p_mid1_fu_705_p1;
wire   [0:0] notrhs_mid3_fu_677_p3;
wire   [0:0] notrhs_mid1_fu_733_p2;
wire   [30:0] k_mid2_fu_697_p3;
wire   [31:0] k_cast_mid2_cast_fu_746_p1;
wire   [0:0] notlhs_mid2_fu_615_p3;
wire   [0:0] tmp_5_fu_758_p2;
wire   [0:0] tmp6_fu_763_p2;
wire   [0:0] notrhs_mid2_fu_738_p3;
wire  signed [8:0] grp_fu_1108_p3;
wire   [63:0] indvar_flatten_op_fu_796_p2;
wire   [25:0] sel_tmp5_fu_810_p3;
wire   [25:0] sel_tmp7_fu_817_p3;
wire   [25:0] p_Val2_s_fu_824_p3;
wire  signed [26:0] tmp_14_fu_831_p1;
wire  signed [26:0] tmp_15_fu_835_p1;
wire   [26:0] p_Val2_2_fu_839_p2;
wire   [25:0] p_Val2_3_fu_853_p2;
wire   [0:0] newsignbit_fu_859_p3;
wire   [0:0] isneg_fu_845_p3;
wire   [0:0] tmp_16_fu_867_p2;
wire   [0:0] isneg_not_fu_885_p2;
wire   [0:0] brmerge_i_i1_fu_879_p2;
wire   [0:0] underflow_fu_873_p2;
wire   [0:0] brmerge_fu_891_p2;
wire   [25:0] p_Val2_3_mux_fu_897_p3;
wire   [25:0] p_Val2_3_45_fu_905_p3;
wire   [25:0] sel_tmp1_fu_921_p3;
wire   [25:0] sel_tmp2_fu_928_p3;
wire   [25:0] p_Val2_4_fu_935_p3;
wire  signed [26:0] tmp_17_fu_942_p1;
wire   [26:0] p_Val2_5_fu_946_p2;
wire   [25:0] p_Val2_6_fu_960_p2;
wire   [0:0] newsignbit_1_fu_966_p3;
wire   [0:0] isneg_1_fu_952_p3;
wire   [0:0] tmp_18_fu_974_p2;
wire   [0:0] isneg_1_not_fu_992_p2;
wire   [0:0] brmerge_i_i_fu_986_p2;
wire   [0:0] underflow_1_fu_980_p2;
wire   [0:0] brmerge5_fu_998_p2;
wire   [25:0] p_Val2_6_mux_fu_1004_p3;
wire   [25:0] p_Val2_6_46_fu_1012_p3;
wire   [25:0] tmp_data_data2_V_fu_1020_p3;
wire   [25:0] tmp_data_data1_V_fu_913_p3;
wire   [51:0] tmp_data_fu_1028_p3;
wire   [31:0] k3_cast_fu_1041_p1;
wire   [0:0] tmp_9_fu_1045_p2;
wire   [30:0] j_1_fu_1061_p2;
wire   [30:0] k3_mid2_fu_1067_p3;
wire  signed [8:0] grp_fu_1117_p3;
wire   [4:0] grp_fu_1108_p0;
wire  signed [8:0] grp_fu_1108_p1;
wire   [8:0] grp_fu_1108_p2;
wire   [4:0] grp_fu_1117_p0;
wire  signed [8:0] grp_fu_1117_p1;
wire   [8:0] grp_fu_1117_p2;
wire    ap_CS_fsm_state8;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [63:0] bound_fu_509_p00;
wire   [63:0] bound_fu_509_p10;
reg    ap_condition_793;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_reg_ioackin_output_dma_O_TREADY = 1'b0;
end

top_mac_muladd_5ncud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
top_mac_muladd_5ncud_U230(
    .din0(grp_fu_1108_p0),
    .din1(grp_fu_1108_p1),
    .din2(grp_fu_1108_p2),
    .dout(grp_fu_1108_p3)
);

top_mac_muladd_5ncud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
top_mac_muladd_5ncud_U231(
    .din0(grp_fu_1117_p0),
    .din1(grp_fu_1117_p1),
    .din2(grp_fu_1117_p2),
    .dout(grp_fu_1117_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_output_dma_O_TREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_793)) begin
            if ((1'b0 == ap_block_pp1_stage0_11001)) begin
                ap_reg_ioackin_output_dma_O_TREADY <= 1'b0;
            end else if (((1'b0 == ap_block_pp1_stage0_01001) & (output_dma_O_TREADY == 1'b1))) begin
                ap_reg_ioackin_output_dma_O_TREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_reg_1181 == 1'd0))) begin
        i1_reg_390 <= tmp_4_mid2_v_reg_1190;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i1_reg_390 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd0))) begin
        i_reg_368 <= i_1_fu_473_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_368 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        indvar_flatten1_reg_379 <= indvar_flatten_next1_fu_557_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten1_reg_379 <= 66'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten2_reg_434 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        indvar_flatten2_reg_434 <= indvar_flatten_next2_fu_1055_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        indvar_flatten_reg_401 <= indvar_flatten_next_fu_802_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten_reg_401 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j2_reg_445 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        j2_reg_445 <= tmp_7_mid2_v_fu_1075_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        j_reg_412 <= j_mid2_fu_750_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_412 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        k3_reg_456 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        k3_reg_456 <= k_1_fu_1102_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        k_reg_423 <= k_2_fu_790_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        k_reg_423 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound_reg_1160 <= bound_fu_509_p2;
        notrhs_mid_reg_1171 <= notrhs_mid_fu_523_p2;
        tmp_11_mid_reg_1176 <= tmp_11_mid_fu_529_p2;
        tmp_3_reg_1166[65 : 2] <= tmp_3_fu_515_p3[65 : 2];
        tmp_reg_1149 <= tmp_fu_493_p2;
        tmp_s_reg_1155 <= tmp_s_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond_flatten1_reg_1181 <= exitcond_flatten1_fu_552_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        sel_tmp6_mid2_reg_1201 <= sel_tmp6_mid2_fu_649_p3;
        sel_tmp8_mid2_reg_1207 <= sel_tmp8_mid2_fu_669_p3;
        sel_tmp_mid2_reg_1195 <= sel_tmp_mid2_fu_635_p3;
        tmp_last_reg_1218 <= tmp_last_fu_769_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_fu_552_p2 == 1'd0))) begin
        tmp_4_mid2_v_reg_1190 <= tmp_4_mid2_v_fu_590_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        BIAS_V_address0 = tmp_4_mid2_fu_598_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        BIAS_V_address0 = tmp_2_fu_488_p1;
    end else begin
        BIAS_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        BIAS_V_ce0 = 1'b1;
    end else begin
        BIAS_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd0))) begin
        BIAS_V_we0 = 1'b1;
    end else begin
        BIAS_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_0_V_ce0 = 1'b1;
    end else begin
        OFM_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_0_V_ce1 = 1'b1;
    end else begin
        OFM_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_0_V_we1 = 1'b1;
    end else begin
        OFM_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_1_V_ce0 = 1'b1;
    end else begin
        OFM_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_1_V_ce1 = 1'b1;
    end else begin
        OFM_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_1_V_we1 = 1'b1;
    end else begin
        OFM_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_2_V_ce0 = 1'b1;
    end else begin
        OFM_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_2_V_ce1 = 1'b1;
    end else begin
        OFM_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_2_V_we1 = 1'b1;
    end else begin
        OFM_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_3_V_ce0 = 1'b1;
    end else begin
        OFM_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_3_V_ce1 = 1'b1;
    end else begin
        OFM_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_3_V_we1 = 1'b1;
    end else begin
        OFM_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_4_V_ce0 = 1'b1;
    end else begin
        OFM_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_4_V_ce1 = 1'b1;
    end else begin
        OFM_4_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_4_V_we1 = 1'b1;
    end else begin
        OFM_4_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_5_V_ce0 = 1'b1;
    end else begin
        OFM_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_5_V_ce1 = 1'b1;
    end else begin
        OFM_5_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_5_V_we1 = 1'b1;
    end else begin
        OFM_5_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_6_V_ce0 = 1'b1;
    end else begin
        OFM_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_6_V_ce1 = 1'b1;
    end else begin
        OFM_6_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_6_V_we1 = 1'b1;
    end else begin
        OFM_6_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        OFM_7_V_ce0 = 1'b1;
    end else begin
        OFM_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OFM_7_V_ce1 = 1'b1;
    end else begin
        OFM_7_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
        OFM_7_V_we1 = 1'b1;
    end else begin
        OFM_7_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_flatten1_fu_552_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_reg_1181 == 1'd0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i1_phi_fu_394_p4 = tmp_4_mid2_v_reg_1190;
    end else begin
        ap_phi_mux_i1_phi_fu_394_p4 = i1_reg_390;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_output_dma_O_TREADY == 1'b0)) begin
        ap_sig_ioackin_output_dma_O_TREADY = output_dma_O_TREADY;
    end else begin
        ap_sig_ioackin_output_dma_O_TREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd0))) begin
        input_dma_B_TDATA_blk_n = input_dma_B_TVALID;
    end else begin
        input_dma_B_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd0))) begin
        input_dma_B_TREADY = 1'b1;
    end else begin
        input_dma_B_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_reg_1181 == 1'd0) & (1'b0 == ap_block_pp1_stage0))) begin
        output_dma_O_TDATA_blk_n = output_dma_O_TREADY;
    end else begin
        output_dma_O_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_01001) & (ap_reg_ioackin_output_dma_O_TREADY == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_reg_1181 == 1'd0))) begin
        output_dma_O_TVALID = 1'b1;
    end else begin
        output_dma_O_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_467_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_flatten1_fu_552_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_flatten1_fu_552_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (exitcond_flatten2_fu_1050_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BIAS_V_d0 = input_dma_B_TDATA[25:0];

assign OFM_0_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_0_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_0_V_d1 = 26'd0;

assign OFM_1_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_1_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_1_V_d1 = 26'd0;

assign OFM_2_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_2_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_2_V_d1 = 26'd0;

assign OFM_3_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_3_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_3_V_d1 = 26'd0;

assign OFM_4_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_4_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_4_V_d1 = 26'd0;

assign OFM_5_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_5_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_5_V_d1 = 26'd0;

assign OFM_6_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_6_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_6_V_d1 = 26'd0;

assign OFM_7_V_address0 = tmp_14_cast_fu_779_p1;

assign OFM_7_V_address1 = tmp_21_cast_fu_1091_p1;

assign OFM_7_V_d1 = 26'd0;

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_block_state5_io));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_block_state5_io));
end

always @ (*) begin
    ap_block_state2 = ((input_dma_B_TVALID == 1'b0) & (exitcond1_fu_467_p2 == 1'd0));
end

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((ap_sig_ioackin_output_dma_O_TREADY == 1'b0) & (exitcond_flatten1_reg_1181 == 1'd0));
end

assign ap_block_state5_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_793 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten1_reg_1181 == 1'd0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign bound_fu_509_p0 = bound_fu_509_p00;

assign bound_fu_509_p00 = custom_Tr;

assign bound_fu_509_p1 = bound_fu_509_p10;

assign bound_fu_509_p10 = custom_Tc;

assign bound_fu_509_p2 = (bound_fu_509_p0 * bound_fu_509_p1);

assign brmerge5_fu_998_p2 = (newsignbit_1_fu_966_p3 | isneg_1_not_fu_992_p2);

assign brmerge_fu_891_p2 = (newsignbit_fu_859_p3 | isneg_not_fu_885_p2);

assign brmerge_i_i1_fu_879_p2 = (newsignbit_fu_859_p3 ^ isneg_fu_845_p3);

assign brmerge_i_i_fu_986_p2 = (newsignbit_1_fu_966_p3 ^ isneg_1_fu_952_p3);

assign exitcond1_fu_467_p2 = ((i_reg_368 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond_flatten1_fu_552_p2 = ((indvar_flatten1_reg_379 == tmp_3_reg_1166) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_1050_p2 = ((indvar_flatten2_reg_434 == bound_reg_1160) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_569_p2 = ((indvar_flatten_reg_401 == bound_reg_1160) ? 1'b1 : 1'b0);

assign grp_fu_1108_p0 = 9'd13;

assign grp_fu_1108_p1 = ((tmp_11_mid1_fu_684_p3[0:0] === 1'b1) ? tmp_13_fu_713_p3 : tmp_22_fu_721_p1);

assign grp_fu_1108_p2 = k_mid2_fu_697_p3[8:0];

assign grp_fu_1117_p0 = 9'd13;

assign grp_fu_1117_p1 = tmp_7_mid2_v_fu_1075_p3[8:0];

assign grp_fu_1117_p2 = k3_mid2_fu_1067_p3[8:0];

assign i_1_fu_473_p2 = (i_reg_368 + 4'd1);

assign i_2_fu_563_p2 = (3'd1 + ap_phi_mux_i1_phi_fu_394_p4);

assign indvar_flatten_next1_fu_557_p2 = (indvar_flatten1_reg_379 + 66'd1);

assign indvar_flatten_next2_fu_1055_p2 = (indvar_flatten2_reg_434 + 64'd1);

assign indvar_flatten_next_fu_802_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? 64'd1 : indvar_flatten_op_fu_796_p2);

assign indvar_flatten_op_fu_796_p2 = (64'd1 + indvar_flatten_reg_401);

assign isneg_1_fu_952_p3 = p_Val2_5_fu_946_p2[32'd26];

assign isneg_1_not_fu_992_p2 = (isneg_1_fu_952_p3 ^ 1'd1);

assign isneg_fu_845_p3 = p_Val2_2_fu_839_p2[32'd26];

assign isneg_not_fu_885_p2 = (isneg_fu_845_p3 ^ 1'd1);

assign j_1_fu_1061_p2 = (31'd1 + j2_reg_445);

assign j_2_fu_691_p2 = (31'd1 + j_mid_fu_574_p3);

assign j_mid2_fu_750_p3 = ((tmp_11_mid1_fu_684_p3[0:0] === 1'b1) ? j_mid_fu_574_p3 : j_2_fu_691_p2);

assign j_mid_fu_574_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? 31'd0 : j_reg_412);

assign k3_cast_fu_1041_p1 = k3_reg_456;

assign k3_mid2_fu_1067_p3 = ((tmp_9_fu_1045_p2[0:0] === 1'b1) ? k3_reg_456 : 31'd0);

assign k_1_fu_1102_p2 = (31'd1 + k3_mid2_fu_1067_p3);

assign k_2_fu_790_p2 = (31'd1 + k_mid2_fu_697_p3);

assign k_cast_fu_543_p1 = k_reg_423;

assign k_cast_mid2_cast_fu_746_p1 = k_mid2_fu_697_p3;

assign k_mid2_fu_697_p3 = ((tmp_11_mid1_fu_684_p3[0:0] === 1'b1) ? k_mid_fu_582_p3 : 31'd0);

assign k_mid_fu_582_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? 31'd0 : k_reg_423);

assign newsignbit_1_fu_966_p3 = p_Val2_6_fu_960_p2[32'd25];

assign newsignbit_fu_859_p3 = p_Val2_3_fu_853_p2[32'd25];

assign notlhs_fu_609_p2 = ((ap_phi_mux_i1_phi_fu_394_p4 == 3'd3) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_603_p2 = ((i_2_fu_563_p2 == 3'd3) ? 1'b1 : 1'b0);

assign notlhs_mid2_fu_615_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? notlhs_mid1_fu_603_p2 : notlhs_fu_609_p2);

assign notrhs_fu_538_p2 = ((tmp_4_fu_534_p1 == tmp_reg_1149) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_733_p2 = ((p_mid1_fu_705_p1 == tmp_reg_1149) ? 1'b1 : 1'b0);

assign notrhs_mid2_fu_738_p3 = ((tmp_11_mid1_fu_684_p3[0:0] === 1'b1) ? notrhs_mid3_fu_677_p3 : notrhs_mid1_fu_733_p2);

assign notrhs_mid3_fu_677_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? notrhs_mid_reg_1171 : notrhs_fu_538_p2);

assign notrhs_mid_fu_523_p2 = ((tmp_fu_493_p2 == 32'd0) ? 1'b1 : 1'b0);

assign output_dma_O_TDATA = $signed(tmp_data_fu_1028_p3);

assign output_dma_O_TLAST = tmp_last_reg_1218;

assign p_Val2_2_fu_839_p2 = ($signed(tmp_14_fu_831_p1) + $signed(tmp_15_fu_835_p1));

assign p_Val2_3_45_fu_905_p3 = ((underflow_fu_873_p2[0:0] === 1'b1) ? 26'd33554432 : p_Val2_3_fu_853_p2);

assign p_Val2_3_fu_853_p2 = (p_Val2_s_fu_824_p3 + BIAS_V_q0);

assign p_Val2_3_mux_fu_897_p3 = ((brmerge_i_i1_fu_879_p2[0:0] === 1'b1) ? 26'd33554431 : p_Val2_3_fu_853_p2);

assign p_Val2_4_fu_935_p3 = ((sel_tmp8_mid2_reg_1207[0:0] === 1'b1) ? OFM_6_V_q0 : sel_tmp2_fu_928_p3);

assign p_Val2_5_fu_946_p2 = ($signed(tmp_15_fu_835_p1) + $signed(tmp_17_fu_942_p1));

assign p_Val2_6_46_fu_1012_p3 = ((underflow_1_fu_980_p2[0:0] === 1'b1) ? 26'd33554432 : p_Val2_6_fu_960_p2);

assign p_Val2_6_fu_960_p2 = (p_Val2_4_fu_935_p3 + BIAS_V_q0);

assign p_Val2_6_mux_fu_1004_p3 = ((brmerge_i_i_fu_986_p2[0:0] === 1'b1) ? 26'd33554431 : p_Val2_6_fu_960_p2);

assign p_Val2_s_fu_824_p3 = ((sel_tmp8_mid2_reg_1207[0:0] === 1'b1) ? OFM_2_V_q0 : sel_tmp7_fu_817_p3);

assign p_mid1_fu_705_p1 = j_2_fu_691_p2;

assign sel_tmp1_fu_921_p3 = ((sel_tmp_mid2_reg_1195[0:0] === 1'b1) ? OFM_4_V_q0 : OFM_7_V_q0);

assign sel_tmp2_fu_928_p3 = ((sel_tmp6_mid2_reg_1201[0:0] === 1'b1) ? OFM_5_V_q0 : sel_tmp1_fu_921_p3);

assign sel_tmp3_fu_643_p2 = ((ap_phi_mux_i1_phi_fu_394_p4 == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_663_p2 = ((ap_phi_mux_i1_phi_fu_394_p4 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_810_p3 = ((sel_tmp_mid2_reg_1195[0:0] === 1'b1) ? OFM_0_V_q0 : OFM_3_V_q0);

assign sel_tmp6_mid2_fu_649_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? sel_tmp_fu_629_p2 : sel_tmp3_fu_643_p2);

assign sel_tmp7_fu_817_p3 = ((sel_tmp6_mid2_reg_1201[0:0] === 1'b1) ? OFM_1_V_q0 : sel_tmp5_fu_810_p3);

assign sel_tmp8_mid1_fu_657_p2 = ((i_2_fu_563_p2 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp8_mid2_fu_669_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? sel_tmp8_mid1_fu_657_p2 : sel_tmp4_fu_663_p2);

assign sel_tmp_fu_629_p2 = ((ap_phi_mux_i1_phi_fu_394_p4 == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp_mid1_fu_623_p2 = ((i_2_fu_563_p2 == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp_mid2_fu_635_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? sel_tmp_mid1_fu_623_p2 : sel_tmp_fu_629_p2);

assign tmp6_fu_763_p2 = (tmp_5_fu_758_p2 & notlhs_mid2_fu_615_p3);

assign tmp_11_fu_709_p1 = j_reg_412[8:0];

assign tmp_11_mid1_fu_684_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? tmp_11_mid_reg_1176 : tmp_6_fu_547_p2);

assign tmp_11_mid_fu_529_p2 = (($signed(custom_Tc) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_13_fu_713_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? 9'd0 : tmp_11_fu_709_p1);

assign tmp_14_cast_fu_779_p1 = grp_fu_1108_p3;

assign tmp_14_fu_831_p1 = $signed(p_Val2_s_fu_824_p3);

assign tmp_15_fu_835_p1 = $signed(BIAS_V_q0);

assign tmp_16_fu_867_p2 = (newsignbit_fu_859_p3 ^ 1'd1);

assign tmp_17_fu_942_p1 = $signed(p_Val2_4_fu_935_p3);

assign tmp_18_fu_974_p2 = (newsignbit_1_fu_966_p3 ^ 1'd1);

assign tmp_21_cast_fu_1091_p1 = grp_fu_1117_p3;

assign tmp_22_fu_721_p1 = j_2_fu_691_p2[8:0];

assign tmp_2_fu_488_p1 = i_reg_368;

assign tmp_3_fu_515_p3 = {{bound_fu_509_p2}, {2'd0}};

assign tmp_4_fu_534_p1 = j_reg_412;

assign tmp_4_mid2_fu_598_p1 = tmp_4_mid2_v_fu_590_p3;

assign tmp_4_mid2_v_fu_590_p3 = ((exitcond_flatten_fu_569_p2[0:0] === 1'b1) ? i_2_fu_563_p2 : ap_phi_mux_i1_phi_fu_394_p4);

assign tmp_5_fu_758_p2 = ((k_cast_mid2_cast_fu_746_p1 == tmp_s_reg_1155) ? 1'b1 : 1'b0);

assign tmp_6_fu_547_p2 = (($signed(k_cast_fu_543_p1) < $signed(custom_Tc)) ? 1'b1 : 1'b0);

assign tmp_7_mid2_v_fu_1075_p3 = ((tmp_9_fu_1045_p2[0:0] === 1'b1) ? j2_reg_445 : j_1_fu_1061_p2);

assign tmp_9_fu_1045_p2 = (($signed(k3_cast_fu_1041_p1) < $signed(custom_Tc)) ? 1'b1 : 1'b0);

assign tmp_data_data1_V_fu_913_p3 = ((brmerge_fu_891_p2[0:0] === 1'b1) ? p_Val2_3_mux_fu_897_p3 : p_Val2_3_45_fu_905_p3);

assign tmp_data_data2_V_fu_1020_p3 = ((brmerge5_fu_998_p2[0:0] === 1'b1) ? p_Val2_6_mux_fu_1004_p3 : p_Val2_6_46_fu_1012_p3);

assign tmp_data_fu_1028_p3 = {{tmp_data_data2_V_fu_1020_p3}, {tmp_data_data1_V_fu_913_p3}};

assign tmp_fu_493_p2 = ($signed(custom_Tr) + $signed(32'd4294967295));

assign tmp_last_fu_769_p2 = (tmp6_fu_763_p2 & notrhs_mid2_fu_738_p3);

assign tmp_s_fu_498_p2 = ($signed(custom_Tc) + $signed(32'd4294967295));

assign underflow_1_fu_980_p2 = (tmp_18_fu_974_p2 & isneg_1_fu_952_p3);

assign underflow_fu_873_p2 = (tmp_16_fu_867_p2 & isneg_fu_845_p3);

always @ (posedge ap_clk) begin
    tmp_3_reg_1166[1:0] <= 2'b00;
end

endmodule //OFM_STORE
