// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CRTL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of row
//        bit 31~0 - row[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of col
//        bit 31~0 - col[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of flag
//        bit 31~0 - flag[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of num
//        bit 31~0 - num[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of N
//        bit 31~0 - N[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of custom_k
//        bit 31~0 - custom_k[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of custom_Tr
//        bit 31~0 - custom_Tr[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of custom_Tc
//        bit 31~0 - custom_Tc[31:0] (Read/Write)
// 0x4c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTOP_CRTL_BUS_ADDR_AP_CTRL        0x00
#define XTOP_CRTL_BUS_ADDR_GIE            0x04
#define XTOP_CRTL_BUS_ADDR_IER            0x08
#define XTOP_CRTL_BUS_ADDR_ISR            0x0c
#define XTOP_CRTL_BUS_ADDR_ROW_DATA       0x10
#define XTOP_CRTL_BUS_BITS_ROW_DATA       32
#define XTOP_CRTL_BUS_ADDR_COL_DATA       0x18
#define XTOP_CRTL_BUS_BITS_COL_DATA       32
#define XTOP_CRTL_BUS_ADDR_FLAG_DATA      0x20
#define XTOP_CRTL_BUS_BITS_FLAG_DATA      32
#define XTOP_CRTL_BUS_ADDR_NUM_DATA       0x28
#define XTOP_CRTL_BUS_BITS_NUM_DATA       32
#define XTOP_CRTL_BUS_ADDR_N_DATA         0x30
#define XTOP_CRTL_BUS_BITS_N_DATA         32
#define XTOP_CRTL_BUS_ADDR_CUSTOM_K_DATA  0x38
#define XTOP_CRTL_BUS_BITS_CUSTOM_K_DATA  32
#define XTOP_CRTL_BUS_ADDR_CUSTOM_TR_DATA 0x40
#define XTOP_CRTL_BUS_BITS_CUSTOM_TR_DATA 32
#define XTOP_CRTL_BUS_ADDR_CUSTOM_TC_DATA 0x48
#define XTOP_CRTL_BUS_BITS_CUSTOM_TC_DATA 32

