// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "OFM_STORE.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic OFM_STORE::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic OFM_STORE::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> OFM_STORE::ap_ST_fsm_state1 = "1";
const sc_lv<7> OFM_STORE::ap_ST_fsm_state2 = "10";
const sc_lv<7> OFM_STORE::ap_ST_fsm_state3 = "100";
const sc_lv<7> OFM_STORE::ap_ST_fsm_pp1_stage0 = "1000";
const sc_lv<7> OFM_STORE::ap_ST_fsm_state6 = "10000";
const sc_lv<7> OFM_STORE::ap_ST_fsm_state7 = "100000";
const sc_lv<7> OFM_STORE::ap_ST_fsm_state8 = "1000000";
const bool OFM_STORE::ap_const_boolean_1 = true;
const sc_lv<32> OFM_STORE::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> OFM_STORE::ap_const_lv32_3 = "11";
const bool OFM_STORE::ap_const_boolean_0 = false;
const sc_lv<1> OFM_STORE::ap_const_lv1_0 = "0";
const sc_lv<32> OFM_STORE::ap_const_lv32_1 = "1";
const sc_lv<32> OFM_STORE::ap_const_lv32_2 = "10";
const sc_lv<32> OFM_STORE::ap_const_lv32_5 = "101";
const sc_lv<1> OFM_STORE::ap_const_lv1_1 = "1";
const sc_lv<4> OFM_STORE::ap_const_lv4_0 = "0000";
const sc_lv<66> OFM_STORE::ap_const_lv66_0 = "000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<3> OFM_STORE::ap_const_lv3_0 = "000";
const sc_lv<64> OFM_STORE::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<31> OFM_STORE::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> OFM_STORE::ap_const_lv32_4 = "100";
const sc_lv<26> OFM_STORE::ap_const_lv26_0 = "00000000000000000000000000";
const sc_lv<4> OFM_STORE::ap_const_lv4_8 = "1000";
const sc_lv<4> OFM_STORE::ap_const_lv4_1 = "1";
const sc_lv<32> OFM_STORE::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<2> OFM_STORE::ap_const_lv2_0 = "00";
const sc_lv<66> OFM_STORE::ap_const_lv66_1 = "1";
const sc_lv<3> OFM_STORE::ap_const_lv3_1 = "1";
const sc_lv<3> OFM_STORE::ap_const_lv3_3 = "11";
const sc_lv<3> OFM_STORE::ap_const_lv3_2 = "10";
const sc_lv<31> OFM_STORE::ap_const_lv31_1 = "1";
const sc_lv<9> OFM_STORE::ap_const_lv9_0 = "000000000";
const sc_lv<64> OFM_STORE::ap_const_lv64_1 = "1";
const sc_lv<32> OFM_STORE::ap_const_lv32_1A = "11010";
const sc_lv<32> OFM_STORE::ap_const_lv32_19 = "11001";
const sc_lv<26> OFM_STORE::ap_const_lv26_1FFFFFF = "1111111111111111111111111";
const sc_lv<26> OFM_STORE::ap_const_lv26_2000000 = "10000000000000000000000000";
const sc_lv<9> OFM_STORE::ap_const_lv9_D = "1101";
const sc_lv<32> OFM_STORE::ap_const_lv32_6 = "110";

OFM_STORE::OFM_STORE(sc_module_name name) : sc_module(name), mVcdFile(0) {
    top_mac_muladd_5ncud_U230 = new top_mac_muladd_5ncud<1,1,5,9,9,9>("top_mac_muladd_5ncud_U230");
    top_mac_muladd_5ncud_U230->din0(grp_fu_1108_p0);
    top_mac_muladd_5ncud_U230->din1(grp_fu_1108_p1);
    top_mac_muladd_5ncud_U230->din2(grp_fu_1108_p2);
    top_mac_muladd_5ncud_U230->dout(grp_fu_1108_p3);
    top_mac_muladd_5ncud_U231 = new top_mac_muladd_5ncud<1,1,5,9,9,9>("top_mac_muladd_5ncud_U231");
    top_mac_muladd_5ncud_U231->din0(grp_fu_1117_p0);
    top_mac_muladd_5ncud_U231->din1(grp_fu_1117_p1);
    top_mac_muladd_5ncud_U231->din2(grp_fu_1117_p2);
    top_mac_muladd_5ncud_U231->dout(grp_fu_1117_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_BIAS_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_2_fu_488_p1 );
    sensitive << ( tmp_4_mid2_fu_598_p1 );

    SC_METHOD(thread_BIAS_V_ce0);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_BIAS_V_d0);
    sensitive << ( input_dma_B_TDATA );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_BIAS_V_we0);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );

    SC_METHOD(thread_OFM_0_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_0_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_0_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_0_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_0_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_1_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_1_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_1_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_1_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_1_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_1_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_2_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_2_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_2_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_2_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_2_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_2_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_3_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_3_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_3_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_3_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_3_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_3_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_4_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_4_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_4_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_4_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_4_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_4_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_5_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_5_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_5_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_5_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_5_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_5_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_6_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_6_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_6_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_6_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_6_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_6_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_OFM_7_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_14_cast_fu_779_p1 );

    SC_METHOD(thread_OFM_7_V_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_21_cast_fu_1091_p1 );

    SC_METHOD(thread_OFM_7_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_OFM_7_V_ce1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_7_V_d1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OFM_7_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( exitcond1_fu_467_p2 );

    SC_METHOD(thread_ap_block_state4_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_io);
    sensitive << ( exitcond_flatten1_reg_1181 );
    sensitive << ( ap_sig_ioackin_output_dma_O_TREADY );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter1);

    SC_METHOD(thread_ap_condition_793);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond_flatten1_reg_1181 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state4);
    sensitive << ( exitcond_flatten1_fu_552_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_i1_phi_fu_394_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_flatten1_reg_1181 );
    sensitive << ( i1_reg_390 );
    sensitive << ( tmp_4_mid2_v_reg_1190 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_sig_ioackin_output_dma_O_TREADY);
    sensitive << ( output_dma_O_TREADY );
    sensitive << ( ap_reg_ioackin_output_dma_O_TREADY );

    SC_METHOD(thread_bound_fu_509_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( bound_fu_509_p00 );

    SC_METHOD(thread_bound_fu_509_p00);
    sensitive << ( custom_Tr );

    SC_METHOD(thread_bound_fu_509_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( bound_fu_509_p10 );

    SC_METHOD(thread_bound_fu_509_p10);
    sensitive << ( custom_Tc );

    SC_METHOD(thread_bound_fu_509_p2);
    sensitive << ( bound_fu_509_p0 );
    sensitive << ( bound_fu_509_p1 );

    SC_METHOD(thread_brmerge5_fu_998_p2);
    sensitive << ( newsignbit_1_fu_966_p3 );
    sensitive << ( isneg_1_not_fu_992_p2 );

    SC_METHOD(thread_brmerge_fu_891_p2);
    sensitive << ( newsignbit_fu_859_p3 );
    sensitive << ( isneg_not_fu_885_p2 );

    SC_METHOD(thread_brmerge_i_i1_fu_879_p2);
    sensitive << ( newsignbit_fu_859_p3 );
    sensitive << ( isneg_fu_845_p3 );

    SC_METHOD(thread_brmerge_i_i_fu_986_p2);
    sensitive << ( newsignbit_1_fu_966_p3 );
    sensitive << ( isneg_1_fu_952_p3 );

    SC_METHOD(thread_exitcond1_fu_467_p2);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );
    sensitive << ( i_reg_368 );

    SC_METHOD(thread_exitcond_flatten1_fu_552_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten1_reg_379 );
    sensitive << ( tmp_3_reg_1166 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_exitcond_flatten2_fu_1050_p2);
    sensitive << ( bound_reg_1160 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( indvar_flatten2_reg_434 );

    SC_METHOD(thread_exitcond_flatten_fu_569_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( indvar_flatten_reg_401 );
    sensitive << ( bound_reg_1160 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_grp_fu_1108_p0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_grp_fu_1108_p1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_11_mid1_fu_684_p3 );
    sensitive << ( tmp_13_fu_713_p3 );
    sensitive << ( tmp_22_fu_721_p1 );

    SC_METHOD(thread_grp_fu_1108_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( k_mid2_fu_697_p3 );

    SC_METHOD(thread_grp_fu_1117_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_grp_fu_1117_p1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_7_mid2_v_fu_1075_p3 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );

    SC_METHOD(thread_grp_fu_1117_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );
    sensitive << ( k3_mid2_fu_1067_p3 );

    SC_METHOD(thread_i_1_fu_473_p2);
    sensitive << ( i_reg_368 );

    SC_METHOD(thread_i_2_fu_563_p2);
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );

    SC_METHOD(thread_indvar_flatten_next1_fu_557_p2);
    sensitive << ( indvar_flatten1_reg_379 );

    SC_METHOD(thread_indvar_flatten_next2_fu_1055_p2);
    sensitive << ( indvar_flatten2_reg_434 );

    SC_METHOD(thread_indvar_flatten_next_fu_802_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( indvar_flatten_op_fu_796_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_796_p2);
    sensitive << ( indvar_flatten_reg_401 );

    SC_METHOD(thread_input_dma_B_TDATA_blk_n);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );

    SC_METHOD(thread_input_dma_B_TREADY);
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );

    SC_METHOD(thread_isneg_1_fu_952_p3);
    sensitive << ( p_Val2_5_fu_946_p2 );

    SC_METHOD(thread_isneg_1_not_fu_992_p2);
    sensitive << ( isneg_1_fu_952_p3 );

    SC_METHOD(thread_isneg_fu_845_p3);
    sensitive << ( p_Val2_2_fu_839_p2 );

    SC_METHOD(thread_isneg_not_fu_885_p2);
    sensitive << ( isneg_fu_845_p3 );

    SC_METHOD(thread_j_1_fu_1061_p2);
    sensitive << ( j2_reg_445 );

    SC_METHOD(thread_j_2_fu_691_p2);
    sensitive << ( j_mid_fu_574_p3 );

    SC_METHOD(thread_j_mid2_fu_750_p3);
    sensitive << ( j_mid_fu_574_p3 );
    sensitive << ( tmp_11_mid1_fu_684_p3 );
    sensitive << ( j_2_fu_691_p2 );

    SC_METHOD(thread_j_mid_fu_574_p3);
    sensitive << ( j_reg_412 );
    sensitive << ( exitcond_flatten_fu_569_p2 );

    SC_METHOD(thread_k3_cast_fu_1041_p1);
    sensitive << ( k3_reg_456 );

    SC_METHOD(thread_k3_mid2_fu_1067_p3);
    sensitive << ( k3_reg_456 );
    sensitive << ( tmp_9_fu_1045_p2 );

    SC_METHOD(thread_k_1_fu_1102_p2);
    sensitive << ( k3_mid2_fu_1067_p3 );

    SC_METHOD(thread_k_2_fu_790_p2);
    sensitive << ( k_mid2_fu_697_p3 );

    SC_METHOD(thread_k_cast_fu_543_p1);
    sensitive << ( k_reg_423 );

    SC_METHOD(thread_k_cast_mid2_cast_fu_746_p1);
    sensitive << ( k_mid2_fu_697_p3 );

    SC_METHOD(thread_k_mid2_fu_697_p3);
    sensitive << ( tmp_11_mid1_fu_684_p3 );
    sensitive << ( k_mid_fu_582_p3 );

    SC_METHOD(thread_k_mid_fu_582_p3);
    sensitive << ( k_reg_423 );
    sensitive << ( exitcond_flatten_fu_569_p2 );

    SC_METHOD(thread_newsignbit_1_fu_966_p3);
    sensitive << ( p_Val2_6_fu_960_p2 );

    SC_METHOD(thread_newsignbit_fu_859_p3);
    sensitive << ( p_Val2_3_fu_853_p2 );

    SC_METHOD(thread_notlhs_fu_609_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );

    SC_METHOD(thread_notlhs_mid1_fu_603_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( i_2_fu_563_p2 );

    SC_METHOD(thread_notlhs_mid2_fu_615_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( notlhs_mid1_fu_603_p2 );
    sensitive << ( notlhs_fu_609_p2 );

    SC_METHOD(thread_notrhs_fu_538_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( tmp_reg_1149 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_4_fu_534_p1 );

    SC_METHOD(thread_notrhs_mid1_fu_733_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( tmp_reg_1149 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( p_mid1_fu_705_p1 );

    SC_METHOD(thread_notrhs_mid2_fu_738_p3);
    sensitive << ( tmp_11_mid1_fu_684_p3 );
    sensitive << ( notrhs_mid3_fu_677_p3 );
    sensitive << ( notrhs_mid1_fu_733_p2 );

    SC_METHOD(thread_notrhs_mid3_fu_677_p3);
    sensitive << ( notrhs_mid_reg_1171 );
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( notrhs_fu_538_p2 );

    SC_METHOD(thread_notrhs_mid_fu_523_p2);
    sensitive << ( tmp_fu_493_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_output_dma_O_TDATA);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond_flatten1_reg_1181 );
    sensitive << ( ap_block_pp1_stage0_01001 );
    sensitive << ( tmp_data_fu_1028_p3 );

    SC_METHOD(thread_output_dma_O_TDATA_blk_n);
    sensitive << ( output_dma_O_TREADY );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_flatten1_reg_1181 );

    SC_METHOD(thread_output_dma_O_TLAST);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond_flatten1_reg_1181 );
    sensitive << ( tmp_last_reg_1218 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_output_dma_O_TVALID);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond_flatten1_reg_1181 );
    sensitive << ( ap_block_pp1_stage0_01001 );
    sensitive << ( ap_reg_ioackin_output_dma_O_TREADY );

    SC_METHOD(thread_p_Val2_2_fu_839_p2);
    sensitive << ( tmp_14_fu_831_p1 );
    sensitive << ( tmp_15_fu_835_p1 );

    SC_METHOD(thread_p_Val2_3_45_fu_905_p3);
    sensitive << ( p_Val2_3_fu_853_p2 );
    sensitive << ( underflow_fu_873_p2 );

    SC_METHOD(thread_p_Val2_3_fu_853_p2);
    sensitive << ( BIAS_V_q0 );
    sensitive << ( p_Val2_s_fu_824_p3 );

    SC_METHOD(thread_p_Val2_3_mux_fu_897_p3);
    sensitive << ( p_Val2_3_fu_853_p2 );
    sensitive << ( brmerge_i_i1_fu_879_p2 );

    SC_METHOD(thread_p_Val2_4_fu_935_p3);
    sensitive << ( OFM_6_V_q0 );
    sensitive << ( sel_tmp8_mid2_reg_1207 );
    sensitive << ( sel_tmp2_fu_928_p3 );

    SC_METHOD(thread_p_Val2_5_fu_946_p2);
    sensitive << ( tmp_15_fu_835_p1 );
    sensitive << ( tmp_17_fu_942_p1 );

    SC_METHOD(thread_p_Val2_6_46_fu_1012_p3);
    sensitive << ( p_Val2_6_fu_960_p2 );
    sensitive << ( underflow_1_fu_980_p2 );

    SC_METHOD(thread_p_Val2_6_fu_960_p2);
    sensitive << ( BIAS_V_q0 );
    sensitive << ( p_Val2_4_fu_935_p3 );

    SC_METHOD(thread_p_Val2_6_mux_fu_1004_p3);
    sensitive << ( p_Val2_6_fu_960_p2 );
    sensitive << ( brmerge_i_i_fu_986_p2 );

    SC_METHOD(thread_p_Val2_s_fu_824_p3);
    sensitive << ( OFM_2_V_q0 );
    sensitive << ( sel_tmp8_mid2_reg_1207 );
    sensitive << ( sel_tmp7_fu_817_p3 );

    SC_METHOD(thread_p_mid1_fu_705_p1);
    sensitive << ( j_2_fu_691_p2 );

    SC_METHOD(thread_sel_tmp1_fu_921_p3);
    sensitive << ( OFM_4_V_q0 );
    sensitive << ( OFM_7_V_q0 );
    sensitive << ( sel_tmp_mid2_reg_1195 );

    SC_METHOD(thread_sel_tmp2_fu_928_p3);
    sensitive << ( OFM_5_V_q0 );
    sensitive << ( sel_tmp6_mid2_reg_1201 );
    sensitive << ( sel_tmp1_fu_921_p3 );

    SC_METHOD(thread_sel_tmp3_fu_643_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );

    SC_METHOD(thread_sel_tmp4_fu_663_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );

    SC_METHOD(thread_sel_tmp5_fu_810_p3);
    sensitive << ( OFM_0_V_q0 );
    sensitive << ( OFM_3_V_q0 );
    sensitive << ( sel_tmp_mid2_reg_1195 );

    SC_METHOD(thread_sel_tmp6_mid2_fu_649_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( sel_tmp_fu_629_p2 );
    sensitive << ( sel_tmp3_fu_643_p2 );

    SC_METHOD(thread_sel_tmp7_fu_817_p3);
    sensitive << ( OFM_1_V_q0 );
    sensitive << ( sel_tmp6_mid2_reg_1201 );
    sensitive << ( sel_tmp5_fu_810_p3 );

    SC_METHOD(thread_sel_tmp8_mid1_fu_657_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( i_2_fu_563_p2 );

    SC_METHOD(thread_sel_tmp8_mid2_fu_669_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( sel_tmp8_mid1_fu_657_p2 );
    sensitive << ( sel_tmp4_fu_663_p2 );

    SC_METHOD(thread_sel_tmp_fu_629_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );

    SC_METHOD(thread_sel_tmp_mid1_fu_623_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( i_2_fu_563_p2 );

    SC_METHOD(thread_sel_tmp_mid2_fu_635_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( sel_tmp_mid1_fu_623_p2 );
    sensitive << ( sel_tmp_fu_629_p2 );

    SC_METHOD(thread_tmp6_fu_763_p2);
    sensitive << ( notlhs_mid2_fu_615_p3 );
    sensitive << ( tmp_5_fu_758_p2 );

    SC_METHOD(thread_tmp_11_fu_709_p1);
    sensitive << ( j_reg_412 );

    SC_METHOD(thread_tmp_11_mid1_fu_684_p3);
    sensitive << ( tmp_11_mid_reg_1176 );
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( tmp_6_fu_547_p2 );

    SC_METHOD(thread_tmp_11_mid_fu_529_p2);
    sensitive << ( custom_Tc );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_13_fu_713_p3);
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( tmp_11_fu_709_p1 );

    SC_METHOD(thread_tmp_14_cast_fu_779_p1);
    sensitive << ( grp_fu_1108_p3 );

    SC_METHOD(thread_tmp_14_fu_831_p1);
    sensitive << ( p_Val2_s_fu_824_p3 );

    SC_METHOD(thread_tmp_15_fu_835_p1);
    sensitive << ( BIAS_V_q0 );

    SC_METHOD(thread_tmp_16_fu_867_p2);
    sensitive << ( newsignbit_fu_859_p3 );

    SC_METHOD(thread_tmp_17_fu_942_p1);
    sensitive << ( p_Val2_4_fu_935_p3 );

    SC_METHOD(thread_tmp_18_fu_974_p2);
    sensitive << ( newsignbit_1_fu_966_p3 );

    SC_METHOD(thread_tmp_21_cast_fu_1091_p1);
    sensitive << ( grp_fu_1117_p3 );

    SC_METHOD(thread_tmp_22_fu_721_p1);
    sensitive << ( j_2_fu_691_p2 );

    SC_METHOD(thread_tmp_2_fu_488_p1);
    sensitive << ( i_reg_368 );

    SC_METHOD(thread_tmp_3_fu_515_p3);
    sensitive << ( bound_fu_509_p2 );

    SC_METHOD(thread_tmp_4_fu_534_p1);
    sensitive << ( j_reg_412 );

    SC_METHOD(thread_tmp_4_mid2_fu_598_p1);
    sensitive << ( tmp_4_mid2_v_fu_590_p3 );

    SC_METHOD(thread_tmp_4_mid2_v_fu_590_p3);
    sensitive << ( ap_phi_mux_i1_phi_fu_394_p4 );
    sensitive << ( exitcond_flatten_fu_569_p2 );
    sensitive << ( i_2_fu_563_p2 );

    SC_METHOD(thread_tmp_5_fu_758_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( tmp_s_reg_1155 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( k_cast_mid2_cast_fu_746_p1 );

    SC_METHOD(thread_tmp_6_fu_547_p2);
    sensitive << ( custom_Tc );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( k_cast_fu_543_p1 );

    SC_METHOD(thread_tmp_7_mid2_v_fu_1075_p3);
    sensitive << ( j2_reg_445 );
    sensitive << ( tmp_9_fu_1045_p2 );
    sensitive << ( j_1_fu_1061_p2 );

    SC_METHOD(thread_tmp_9_fu_1045_p2);
    sensitive << ( custom_Tc );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( k3_cast_fu_1041_p1 );

    SC_METHOD(thread_tmp_data_data1_V_fu_913_p3);
    sensitive << ( brmerge_fu_891_p2 );
    sensitive << ( p_Val2_3_mux_fu_897_p3 );
    sensitive << ( p_Val2_3_45_fu_905_p3 );

    SC_METHOD(thread_tmp_data_data2_V_fu_1020_p3);
    sensitive << ( brmerge5_fu_998_p2 );
    sensitive << ( p_Val2_6_mux_fu_1004_p3 );
    sensitive << ( p_Val2_6_46_fu_1012_p3 );

    SC_METHOD(thread_tmp_data_fu_1028_p3);
    sensitive << ( tmp_data_data2_V_fu_1020_p3 );
    sensitive << ( tmp_data_data1_V_fu_913_p3 );

    SC_METHOD(thread_tmp_fu_493_p2);
    sensitive << ( custom_Tr );

    SC_METHOD(thread_tmp_last_fu_769_p2);
    sensitive << ( tmp6_fu_763_p2 );
    sensitive << ( notrhs_mid2_fu_738_p3 );

    SC_METHOD(thread_tmp_s_fu_498_p2);
    sensitive << ( custom_Tc );

    SC_METHOD(thread_underflow_1_fu_980_p2);
    sensitive << ( isneg_1_fu_952_p3 );
    sensitive << ( tmp_18_fu_974_p2 );

    SC_METHOD(thread_underflow_fu_873_p2);
    sensitive << ( isneg_fu_845_p3 );
    sensitive << ( tmp_16_fu_867_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_dma_B_TVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_467_p2 );
    sensitive << ( exitcond_flatten1_fu_552_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten2_fu_1050_p2 );
    sensitive << ( ap_block_pp1_stage0_subdone );

    ap_CS_fsm = "0000001";
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_reg_ioackin_output_dma_O_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "OFM_STORE_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_dma_O_TDATA, "(port)output_dma_O_TDATA");
    sc_trace(mVcdFile, output_dma_O_TVALID, "(port)output_dma_O_TVALID");
    sc_trace(mVcdFile, output_dma_O_TREADY, "(port)output_dma_O_TREADY");
    sc_trace(mVcdFile, output_dma_O_TLAST, "(port)output_dma_O_TLAST");
    sc_trace(mVcdFile, input_dma_B_TDATA, "(port)input_dma_B_TDATA");
    sc_trace(mVcdFile, input_dma_B_TVALID, "(port)input_dma_B_TVALID");
    sc_trace(mVcdFile, input_dma_B_TREADY, "(port)input_dma_B_TREADY");
    sc_trace(mVcdFile, input_dma_B_TLAST, "(port)input_dma_B_TLAST");
    sc_trace(mVcdFile, OFM_0_V_address0, "(port)OFM_0_V_address0");
    sc_trace(mVcdFile, OFM_0_V_ce0, "(port)OFM_0_V_ce0");
    sc_trace(mVcdFile, OFM_0_V_q0, "(port)OFM_0_V_q0");
    sc_trace(mVcdFile, OFM_0_V_address1, "(port)OFM_0_V_address1");
    sc_trace(mVcdFile, OFM_0_V_ce1, "(port)OFM_0_V_ce1");
    sc_trace(mVcdFile, OFM_0_V_we1, "(port)OFM_0_V_we1");
    sc_trace(mVcdFile, OFM_0_V_d1, "(port)OFM_0_V_d1");
    sc_trace(mVcdFile, OFM_1_V_address0, "(port)OFM_1_V_address0");
    sc_trace(mVcdFile, OFM_1_V_ce0, "(port)OFM_1_V_ce0");
    sc_trace(mVcdFile, OFM_1_V_q0, "(port)OFM_1_V_q0");
    sc_trace(mVcdFile, OFM_1_V_address1, "(port)OFM_1_V_address1");
    sc_trace(mVcdFile, OFM_1_V_ce1, "(port)OFM_1_V_ce1");
    sc_trace(mVcdFile, OFM_1_V_we1, "(port)OFM_1_V_we1");
    sc_trace(mVcdFile, OFM_1_V_d1, "(port)OFM_1_V_d1");
    sc_trace(mVcdFile, OFM_2_V_address0, "(port)OFM_2_V_address0");
    sc_trace(mVcdFile, OFM_2_V_ce0, "(port)OFM_2_V_ce0");
    sc_trace(mVcdFile, OFM_2_V_q0, "(port)OFM_2_V_q0");
    sc_trace(mVcdFile, OFM_2_V_address1, "(port)OFM_2_V_address1");
    sc_trace(mVcdFile, OFM_2_V_ce1, "(port)OFM_2_V_ce1");
    sc_trace(mVcdFile, OFM_2_V_we1, "(port)OFM_2_V_we1");
    sc_trace(mVcdFile, OFM_2_V_d1, "(port)OFM_2_V_d1");
    sc_trace(mVcdFile, OFM_3_V_address0, "(port)OFM_3_V_address0");
    sc_trace(mVcdFile, OFM_3_V_ce0, "(port)OFM_3_V_ce0");
    sc_trace(mVcdFile, OFM_3_V_q0, "(port)OFM_3_V_q0");
    sc_trace(mVcdFile, OFM_3_V_address1, "(port)OFM_3_V_address1");
    sc_trace(mVcdFile, OFM_3_V_ce1, "(port)OFM_3_V_ce1");
    sc_trace(mVcdFile, OFM_3_V_we1, "(port)OFM_3_V_we1");
    sc_trace(mVcdFile, OFM_3_V_d1, "(port)OFM_3_V_d1");
    sc_trace(mVcdFile, OFM_4_V_address0, "(port)OFM_4_V_address0");
    sc_trace(mVcdFile, OFM_4_V_ce0, "(port)OFM_4_V_ce0");
    sc_trace(mVcdFile, OFM_4_V_q0, "(port)OFM_4_V_q0");
    sc_trace(mVcdFile, OFM_4_V_address1, "(port)OFM_4_V_address1");
    sc_trace(mVcdFile, OFM_4_V_ce1, "(port)OFM_4_V_ce1");
    sc_trace(mVcdFile, OFM_4_V_we1, "(port)OFM_4_V_we1");
    sc_trace(mVcdFile, OFM_4_V_d1, "(port)OFM_4_V_d1");
    sc_trace(mVcdFile, OFM_5_V_address0, "(port)OFM_5_V_address0");
    sc_trace(mVcdFile, OFM_5_V_ce0, "(port)OFM_5_V_ce0");
    sc_trace(mVcdFile, OFM_5_V_q0, "(port)OFM_5_V_q0");
    sc_trace(mVcdFile, OFM_5_V_address1, "(port)OFM_5_V_address1");
    sc_trace(mVcdFile, OFM_5_V_ce1, "(port)OFM_5_V_ce1");
    sc_trace(mVcdFile, OFM_5_V_we1, "(port)OFM_5_V_we1");
    sc_trace(mVcdFile, OFM_5_V_d1, "(port)OFM_5_V_d1");
    sc_trace(mVcdFile, OFM_6_V_address0, "(port)OFM_6_V_address0");
    sc_trace(mVcdFile, OFM_6_V_ce0, "(port)OFM_6_V_ce0");
    sc_trace(mVcdFile, OFM_6_V_q0, "(port)OFM_6_V_q0");
    sc_trace(mVcdFile, OFM_6_V_address1, "(port)OFM_6_V_address1");
    sc_trace(mVcdFile, OFM_6_V_ce1, "(port)OFM_6_V_ce1");
    sc_trace(mVcdFile, OFM_6_V_we1, "(port)OFM_6_V_we1");
    sc_trace(mVcdFile, OFM_6_V_d1, "(port)OFM_6_V_d1");
    sc_trace(mVcdFile, OFM_7_V_address0, "(port)OFM_7_V_address0");
    sc_trace(mVcdFile, OFM_7_V_ce0, "(port)OFM_7_V_ce0");
    sc_trace(mVcdFile, OFM_7_V_q0, "(port)OFM_7_V_q0");
    sc_trace(mVcdFile, OFM_7_V_address1, "(port)OFM_7_V_address1");
    sc_trace(mVcdFile, OFM_7_V_ce1, "(port)OFM_7_V_ce1");
    sc_trace(mVcdFile, OFM_7_V_we1, "(port)OFM_7_V_we1");
    sc_trace(mVcdFile, OFM_7_V_d1, "(port)OFM_7_V_d1");
    sc_trace(mVcdFile, BIAS_V_address0, "(port)BIAS_V_address0");
    sc_trace(mVcdFile, BIAS_V_ce0, "(port)BIAS_V_ce0");
    sc_trace(mVcdFile, BIAS_V_we0, "(port)BIAS_V_we0");
    sc_trace(mVcdFile, BIAS_V_d0, "(port)BIAS_V_d0");
    sc_trace(mVcdFile, BIAS_V_q0, "(port)BIAS_V_q0");
    sc_trace(mVcdFile, custom_Tr, "(port)custom_Tr");
    sc_trace(mVcdFile, custom_Tc, "(port)custom_Tc");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, output_dma_O_TDATA_blk_n, "output_dma_O_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, exitcond_flatten1_reg_1181, "exitcond_flatten1_reg_1181");
    sc_trace(mVcdFile, input_dma_B_TDATA_blk_n, "input_dma_B_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond1_fu_467_p2, "exitcond1_fu_467_p2");
    sc_trace(mVcdFile, indvar_flatten1_reg_379, "indvar_flatten1_reg_379");
    sc_trace(mVcdFile, i1_reg_390, "i1_reg_390");
    sc_trace(mVcdFile, indvar_flatten_reg_401, "indvar_flatten_reg_401");
    sc_trace(mVcdFile, j_reg_412, "j_reg_412");
    sc_trace(mVcdFile, k_reg_423, "k_reg_423");
    sc_trace(mVcdFile, i_1_fu_473_p2, "i_1_fu_473_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_fu_493_p2, "tmp_fu_493_p2");
    sc_trace(mVcdFile, tmp_reg_1149, "tmp_reg_1149");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_s_fu_498_p2, "tmp_s_fu_498_p2");
    sc_trace(mVcdFile, tmp_s_reg_1155, "tmp_s_reg_1155");
    sc_trace(mVcdFile, bound_fu_509_p2, "bound_fu_509_p2");
    sc_trace(mVcdFile, bound_reg_1160, "bound_reg_1160");
    sc_trace(mVcdFile, tmp_3_fu_515_p3, "tmp_3_fu_515_p3");
    sc_trace(mVcdFile, tmp_3_reg_1166, "tmp_3_reg_1166");
    sc_trace(mVcdFile, notrhs_mid_fu_523_p2, "notrhs_mid_fu_523_p2");
    sc_trace(mVcdFile, notrhs_mid_reg_1171, "notrhs_mid_reg_1171");
    sc_trace(mVcdFile, tmp_11_mid_fu_529_p2, "tmp_11_mid_fu_529_p2");
    sc_trace(mVcdFile, tmp_11_mid_reg_1176, "tmp_11_mid_reg_1176");
    sc_trace(mVcdFile, exitcond_flatten1_fu_552_p2, "exitcond_flatten1_fu_552_p2");
    sc_trace(mVcdFile, ap_block_state4_pp1_stage0_iter0, "ap_block_state4_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter1, "ap_block_state5_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_sig_ioackin_output_dma_O_TREADY, "ap_sig_ioackin_output_dma_O_TREADY");
    sc_trace(mVcdFile, ap_block_state5_io, "ap_block_state5_io");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_557_p2, "indvar_flatten_next1_fu_557_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, tmp_4_mid2_v_fu_590_p3, "tmp_4_mid2_v_fu_590_p3");
    sc_trace(mVcdFile, tmp_4_mid2_v_reg_1190, "tmp_4_mid2_v_reg_1190");
    sc_trace(mVcdFile, sel_tmp_mid2_fu_635_p3, "sel_tmp_mid2_fu_635_p3");
    sc_trace(mVcdFile, sel_tmp_mid2_reg_1195, "sel_tmp_mid2_reg_1195");
    sc_trace(mVcdFile, sel_tmp6_mid2_fu_649_p3, "sel_tmp6_mid2_fu_649_p3");
    sc_trace(mVcdFile, sel_tmp6_mid2_reg_1201, "sel_tmp6_mid2_reg_1201");
    sc_trace(mVcdFile, sel_tmp8_mid2_fu_669_p3, "sel_tmp8_mid2_fu_669_p3");
    sc_trace(mVcdFile, sel_tmp8_mid2_reg_1207, "sel_tmp8_mid2_reg_1207");
    sc_trace(mVcdFile, j_mid2_fu_750_p3, "j_mid2_fu_750_p3");
    sc_trace(mVcdFile, tmp_last_fu_769_p2, "tmp_last_fu_769_p2");
    sc_trace(mVcdFile, tmp_last_reg_1218, "tmp_last_reg_1218");
    sc_trace(mVcdFile, k_2_fu_790_p2, "k_2_fu_790_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_802_p3, "indvar_flatten_next_fu_802_p3");
    sc_trace(mVcdFile, indvar_flatten_next2_fu_1055_p2, "indvar_flatten_next2_fu_1055_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_7_mid2_v_fu_1075_p3, "tmp_7_mid2_v_fu_1075_p3");
    sc_trace(mVcdFile, exitcond_flatten2_fu_1050_p2, "exitcond_flatten2_fu_1050_p2");
    sc_trace(mVcdFile, k_1_fu_1102_p2, "k_1_fu_1102_p2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state4, "ap_condition_pp1_exit_iter0_state4");
    sc_trace(mVcdFile, i_reg_368, "i_reg_368");
    sc_trace(mVcdFile, ap_phi_mux_i1_phi_fu_394_p4, "ap_phi_mux_i1_phi_fu_394_p4");
    sc_trace(mVcdFile, indvar_flatten2_reg_434, "indvar_flatten2_reg_434");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j2_reg_445, "j2_reg_445");
    sc_trace(mVcdFile, k3_reg_456, "k3_reg_456");
    sc_trace(mVcdFile, tmp_2_fu_488_p1, "tmp_2_fu_488_p1");
    sc_trace(mVcdFile, tmp_14_cast_fu_779_p1, "tmp_14_cast_fu_779_p1");
    sc_trace(mVcdFile, tmp_4_mid2_fu_598_p1, "tmp_4_mid2_fu_598_p1");
    sc_trace(mVcdFile, tmp_21_cast_fu_1091_p1, "tmp_21_cast_fu_1091_p1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, ap_reg_ioackin_output_dma_O_TREADY, "ap_reg_ioackin_output_dma_O_TREADY");
    sc_trace(mVcdFile, bound_fu_509_p0, "bound_fu_509_p0");
    sc_trace(mVcdFile, bound_fu_509_p1, "bound_fu_509_p1");
    sc_trace(mVcdFile, tmp_4_fu_534_p1, "tmp_4_fu_534_p1");
    sc_trace(mVcdFile, k_cast_fu_543_p1, "k_cast_fu_543_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_569_p2, "exitcond_flatten_fu_569_p2");
    sc_trace(mVcdFile, i_2_fu_563_p2, "i_2_fu_563_p2");
    sc_trace(mVcdFile, notlhs_mid1_fu_603_p2, "notlhs_mid1_fu_603_p2");
    sc_trace(mVcdFile, notlhs_fu_609_p2, "notlhs_fu_609_p2");
    sc_trace(mVcdFile, sel_tmp_mid1_fu_623_p2, "sel_tmp_mid1_fu_623_p2");
    sc_trace(mVcdFile, sel_tmp_fu_629_p2, "sel_tmp_fu_629_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_643_p2, "sel_tmp3_fu_643_p2");
    sc_trace(mVcdFile, sel_tmp8_mid1_fu_657_p2, "sel_tmp8_mid1_fu_657_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_663_p2, "sel_tmp4_fu_663_p2");
    sc_trace(mVcdFile, notrhs_fu_538_p2, "notrhs_fu_538_p2");
    sc_trace(mVcdFile, tmp_6_fu_547_p2, "tmp_6_fu_547_p2");
    sc_trace(mVcdFile, j_mid_fu_574_p3, "j_mid_fu_574_p3");
    sc_trace(mVcdFile, tmp_11_mid1_fu_684_p3, "tmp_11_mid1_fu_684_p3");
    sc_trace(mVcdFile, k_mid_fu_582_p3, "k_mid_fu_582_p3");
    sc_trace(mVcdFile, j_2_fu_691_p2, "j_2_fu_691_p2");
    sc_trace(mVcdFile, tmp_11_fu_709_p1, "tmp_11_fu_709_p1");
    sc_trace(mVcdFile, tmp_13_fu_713_p3, "tmp_13_fu_713_p3");
    sc_trace(mVcdFile, tmp_22_fu_721_p1, "tmp_22_fu_721_p1");
    sc_trace(mVcdFile, p_mid1_fu_705_p1, "p_mid1_fu_705_p1");
    sc_trace(mVcdFile, notrhs_mid3_fu_677_p3, "notrhs_mid3_fu_677_p3");
    sc_trace(mVcdFile, notrhs_mid1_fu_733_p2, "notrhs_mid1_fu_733_p2");
    sc_trace(mVcdFile, k_mid2_fu_697_p3, "k_mid2_fu_697_p3");
    sc_trace(mVcdFile, k_cast_mid2_cast_fu_746_p1, "k_cast_mid2_cast_fu_746_p1");
    sc_trace(mVcdFile, notlhs_mid2_fu_615_p3, "notlhs_mid2_fu_615_p3");
    sc_trace(mVcdFile, tmp_5_fu_758_p2, "tmp_5_fu_758_p2");
    sc_trace(mVcdFile, tmp6_fu_763_p2, "tmp6_fu_763_p2");
    sc_trace(mVcdFile, notrhs_mid2_fu_738_p3, "notrhs_mid2_fu_738_p3");
    sc_trace(mVcdFile, grp_fu_1108_p3, "grp_fu_1108_p3");
    sc_trace(mVcdFile, indvar_flatten_op_fu_796_p2, "indvar_flatten_op_fu_796_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_810_p3, "sel_tmp5_fu_810_p3");
    sc_trace(mVcdFile, sel_tmp7_fu_817_p3, "sel_tmp7_fu_817_p3");
    sc_trace(mVcdFile, p_Val2_s_fu_824_p3, "p_Val2_s_fu_824_p3");
    sc_trace(mVcdFile, tmp_14_fu_831_p1, "tmp_14_fu_831_p1");
    sc_trace(mVcdFile, tmp_15_fu_835_p1, "tmp_15_fu_835_p1");
    sc_trace(mVcdFile, p_Val2_2_fu_839_p2, "p_Val2_2_fu_839_p2");
    sc_trace(mVcdFile, p_Val2_3_fu_853_p2, "p_Val2_3_fu_853_p2");
    sc_trace(mVcdFile, newsignbit_fu_859_p3, "newsignbit_fu_859_p3");
    sc_trace(mVcdFile, isneg_fu_845_p3, "isneg_fu_845_p3");
    sc_trace(mVcdFile, tmp_16_fu_867_p2, "tmp_16_fu_867_p2");
    sc_trace(mVcdFile, isneg_not_fu_885_p2, "isneg_not_fu_885_p2");
    sc_trace(mVcdFile, brmerge_i_i1_fu_879_p2, "brmerge_i_i1_fu_879_p2");
    sc_trace(mVcdFile, underflow_fu_873_p2, "underflow_fu_873_p2");
    sc_trace(mVcdFile, brmerge_fu_891_p2, "brmerge_fu_891_p2");
    sc_trace(mVcdFile, p_Val2_3_mux_fu_897_p3, "p_Val2_3_mux_fu_897_p3");
    sc_trace(mVcdFile, p_Val2_3_45_fu_905_p3, "p_Val2_3_45_fu_905_p3");
    sc_trace(mVcdFile, sel_tmp1_fu_921_p3, "sel_tmp1_fu_921_p3");
    sc_trace(mVcdFile, sel_tmp2_fu_928_p3, "sel_tmp2_fu_928_p3");
    sc_trace(mVcdFile, p_Val2_4_fu_935_p3, "p_Val2_4_fu_935_p3");
    sc_trace(mVcdFile, tmp_17_fu_942_p1, "tmp_17_fu_942_p1");
    sc_trace(mVcdFile, p_Val2_5_fu_946_p2, "p_Val2_5_fu_946_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_960_p2, "p_Val2_6_fu_960_p2");
    sc_trace(mVcdFile, newsignbit_1_fu_966_p3, "newsignbit_1_fu_966_p3");
    sc_trace(mVcdFile, isneg_1_fu_952_p3, "isneg_1_fu_952_p3");
    sc_trace(mVcdFile, tmp_18_fu_974_p2, "tmp_18_fu_974_p2");
    sc_trace(mVcdFile, isneg_1_not_fu_992_p2, "isneg_1_not_fu_992_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_986_p2, "brmerge_i_i_fu_986_p2");
    sc_trace(mVcdFile, underflow_1_fu_980_p2, "underflow_1_fu_980_p2");
    sc_trace(mVcdFile, brmerge5_fu_998_p2, "brmerge5_fu_998_p2");
    sc_trace(mVcdFile, p_Val2_6_mux_fu_1004_p3, "p_Val2_6_mux_fu_1004_p3");
    sc_trace(mVcdFile, p_Val2_6_46_fu_1012_p3, "p_Val2_6_46_fu_1012_p3");
    sc_trace(mVcdFile, tmp_data_data2_V_fu_1020_p3, "tmp_data_data2_V_fu_1020_p3");
    sc_trace(mVcdFile, tmp_data_data1_V_fu_913_p3, "tmp_data_data1_V_fu_913_p3");
    sc_trace(mVcdFile, tmp_data_fu_1028_p3, "tmp_data_fu_1028_p3");
    sc_trace(mVcdFile, k3_cast_fu_1041_p1, "k3_cast_fu_1041_p1");
    sc_trace(mVcdFile, tmp_9_fu_1045_p2, "tmp_9_fu_1045_p2");
    sc_trace(mVcdFile, j_1_fu_1061_p2, "j_1_fu_1061_p2");
    sc_trace(mVcdFile, k3_mid2_fu_1067_p3, "k3_mid2_fu_1067_p3");
    sc_trace(mVcdFile, grp_fu_1117_p3, "grp_fu_1117_p3");
    sc_trace(mVcdFile, grp_fu_1108_p0, "grp_fu_1108_p0");
    sc_trace(mVcdFile, grp_fu_1108_p1, "grp_fu_1108_p1");
    sc_trace(mVcdFile, grp_fu_1108_p2, "grp_fu_1108_p2");
    sc_trace(mVcdFile, grp_fu_1117_p0, "grp_fu_1117_p0");
    sc_trace(mVcdFile, grp_fu_1117_p1, "grp_fu_1117_p1");
    sc_trace(mVcdFile, grp_fu_1117_p2, "grp_fu_1117_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, bound_fu_509_p00, "bound_fu_509_p00");
    sc_trace(mVcdFile, bound_fu_509_p10, "bound_fu_509_p10");
    sc_trace(mVcdFile, ap_condition_793, "ap_condition_793");
#endif

    }
}

OFM_STORE::~OFM_STORE() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete top_mac_muladd_5ncud_U230;
    delete top_mac_muladd_5ncud_U231;
}

void OFM_STORE::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state4.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state4.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_output_dma_O_TREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_condition_793.read(), ap_const_boolean_1)) {
            if (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_output_dma_O_TREADY = ap_const_logic_0;
            } else if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_01001.read(), ap_const_boolean_0) && 
                        esl_seteq<1,1,1>(ap_const_logic_1, output_dma_O_TREADY.read()))) {
                ap_reg_ioackin_output_dma_O_TREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        i1_reg_390 = tmp_4_mid2_v_reg_1190.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i1_reg_390 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read())))) {
        i_reg_368 = i_1_fu_473_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_368 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        indvar_flatten1_reg_379 = indvar_flatten_next1_fu_557_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten1_reg_379 = ap_const_lv66_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten2_reg_434 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        indvar_flatten2_reg_434 = indvar_flatten_next2_fu_1055_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        indvar_flatten_reg_401 = indvar_flatten_next_fu_802_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten_reg_401 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j2_reg_445 = ap_const_lv31_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        j2_reg_445 = tmp_7_mid2_v_fu_1075_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        j_reg_412 = j_mid2_fu_750_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_412 = ap_const_lv31_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        k3_reg_456 = ap_const_lv31_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        k3_reg_456 = k_1_fu_1102_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        k_reg_423 = k_2_fu_790_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        k_reg_423 = ap_const_lv31_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        bound_reg_1160 = bound_fu_509_p2.read();
        notrhs_mid_reg_1171 = notrhs_mid_fu_523_p2.read();
        tmp_11_mid_reg_1176 = tmp_11_mid_fu_529_p2.read();
        tmp_3_reg_1166 = tmp_3_fu_515_p3.read();
        tmp_reg_1149 = tmp_fu_493_p2.read();
        tmp_s_reg_1155 = tmp_s_fu_498_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten1_reg_1181 = exitcond_flatten1_fu_552_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        sel_tmp6_mid2_reg_1201 = sel_tmp6_mid2_fu_649_p3.read();
        sel_tmp8_mid2_reg_1207 = sel_tmp8_mid2_fu_669_p3.read();
        sel_tmp_mid2_reg_1195 = sel_tmp_mid2_fu_635_p3.read();
        tmp_last_reg_1218 = tmp_last_fu_769_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_552_p2.read()))) {
        tmp_4_mid2_v_reg_1190 = tmp_4_mid2_v_fu_590_p3.read();
    }
}

void OFM_STORE::thread_BIAS_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        BIAS_V_address0 =  (sc_lv<3>) (tmp_4_mid2_fu_598_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        BIAS_V_address0 =  (sc_lv<3>) (tmp_2_fu_488_p1.read());
    } else {
        BIAS_V_address0 = "XXX";
    }
}

void OFM_STORE::thread_BIAS_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())))) {
        BIAS_V_ce0 = ap_const_logic_1;
    } else {
        BIAS_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_BIAS_V_d0() {
    BIAS_V_d0 = input_dma_B_TDATA.read().range(26-1, 0);
}

void OFM_STORE::thread_BIAS_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read())))) {
        BIAS_V_we0 = ap_const_logic_1;
    } else {
        BIAS_V_we0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_0_V_address0() {
    OFM_0_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_0_V_address1() {
    OFM_0_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_0_V_ce0 = ap_const_logic_1;
    } else {
        OFM_0_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_0_V_ce1 = ap_const_logic_1;
    } else {
        OFM_0_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_0_V_d1() {
    OFM_0_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_0_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_0_V_we1 = ap_const_logic_1;
    } else {
        OFM_0_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_1_V_address0() {
    OFM_1_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_1_V_address1() {
    OFM_1_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_1_V_ce0 = ap_const_logic_1;
    } else {
        OFM_1_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_1_V_ce1 = ap_const_logic_1;
    } else {
        OFM_1_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_1_V_d1() {
    OFM_1_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_1_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_1_V_we1 = ap_const_logic_1;
    } else {
        OFM_1_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_2_V_address0() {
    OFM_2_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_2_V_address1() {
    OFM_2_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_2_V_ce0 = ap_const_logic_1;
    } else {
        OFM_2_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_2_V_ce1 = ap_const_logic_1;
    } else {
        OFM_2_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_2_V_d1() {
    OFM_2_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_2_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_2_V_we1 = ap_const_logic_1;
    } else {
        OFM_2_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_3_V_address0() {
    OFM_3_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_3_V_address1() {
    OFM_3_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_3_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_3_V_ce0 = ap_const_logic_1;
    } else {
        OFM_3_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_3_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_3_V_ce1 = ap_const_logic_1;
    } else {
        OFM_3_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_3_V_d1() {
    OFM_3_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_3_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_3_V_we1 = ap_const_logic_1;
    } else {
        OFM_3_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_4_V_address0() {
    OFM_4_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_4_V_address1() {
    OFM_4_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_4_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_4_V_ce0 = ap_const_logic_1;
    } else {
        OFM_4_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_4_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_4_V_ce1 = ap_const_logic_1;
    } else {
        OFM_4_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_4_V_d1() {
    OFM_4_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_4_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_4_V_we1 = ap_const_logic_1;
    } else {
        OFM_4_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_5_V_address0() {
    OFM_5_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_5_V_address1() {
    OFM_5_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_5_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_5_V_ce0 = ap_const_logic_1;
    } else {
        OFM_5_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_5_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_5_V_ce1 = ap_const_logic_1;
    } else {
        OFM_5_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_5_V_d1() {
    OFM_5_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_5_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_5_V_we1 = ap_const_logic_1;
    } else {
        OFM_5_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_6_V_address0() {
    OFM_6_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_6_V_address1() {
    OFM_6_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_6_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_6_V_ce0 = ap_const_logic_1;
    } else {
        OFM_6_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_6_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_6_V_ce1 = ap_const_logic_1;
    } else {
        OFM_6_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_6_V_d1() {
    OFM_6_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_6_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_6_V_we1 = ap_const_logic_1;
    } else {
        OFM_6_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_7_V_address0() {
    OFM_7_V_address0 =  (sc_lv<8>) (tmp_14_cast_fu_779_p1.read());
}

void OFM_STORE::thread_OFM_7_V_address1() {
    OFM_7_V_address1 =  (sc_lv<8>) (tmp_21_cast_fu_1091_p1.read());
}

void OFM_STORE::thread_OFM_7_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        OFM_7_V_ce0 = ap_const_logic_1;
    } else {
        OFM_7_V_ce0 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_7_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OFM_7_V_ce1 = ap_const_logic_1;
    } else {
        OFM_7_V_ce1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_OFM_7_V_d1() {
    OFM_7_V_d1 = ap_const_lv26_0;
}

void OFM_STORE::thread_OFM_7_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
        OFM_7_V_we1 = ap_const_logic_1;
    } else {
        OFM_7_V_we1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[3];
}

void OFM_STORE::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void OFM_STORE::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void OFM_STORE::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void OFM_STORE::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void OFM_STORE::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void OFM_STORE::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void OFM_STORE::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void OFM_STORE::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void OFM_STORE::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read()));
}

void OFM_STORE::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read()));
}

void OFM_STORE::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read()));
}

void OFM_STORE::thread_ap_block_state4_pp1_stage0_iter0() {
    ap_block_state4_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void OFM_STORE::thread_ap_block_state5_io() {
    ap_block_state5_io = (esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_output_dma_O_TREADY.read()));
}

void OFM_STORE::thread_ap_block_state5_pp1_stage0_iter1() {
    ap_block_state5_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void OFM_STORE::thread_ap_condition_793() {
    ap_condition_793 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0));
}

void OFM_STORE::thread_ap_condition_pp1_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_flatten1_fu_552_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state4 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void OFM_STORE::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_phi_mux_i1_phi_fu_394_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0))) {
        ap_phi_mux_i1_phi_fu_394_p4 = tmp_4_mid2_v_reg_1190.read();
    } else {
        ap_phi_mux_i1_phi_fu_394_p4 = i1_reg_390.read();
    }
}

void OFM_STORE::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void OFM_STORE::thread_ap_sig_ioackin_output_dma_O_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_output_dma_O_TREADY.read())) {
        ap_sig_ioackin_output_dma_O_TREADY = output_dma_O_TREADY.read();
    } else {
        ap_sig_ioackin_output_dma_O_TREADY = ap_const_logic_1;
    }
}

void OFM_STORE::thread_bound_fu_509_p0() {
    bound_fu_509_p0 =  (sc_lv<32>) (bound_fu_509_p00.read());
}

void OFM_STORE::thread_bound_fu_509_p00() {
    bound_fu_509_p00 = esl_zext<64,32>(custom_Tr.read());
}

void OFM_STORE::thread_bound_fu_509_p1() {
    bound_fu_509_p1 =  (sc_lv<32>) (bound_fu_509_p10.read());
}

void OFM_STORE::thread_bound_fu_509_p10() {
    bound_fu_509_p10 = esl_zext<64,32>(custom_Tc.read());
}

void OFM_STORE::thread_bound_fu_509_p2() {
    bound_fu_509_p2 = (!bound_fu_509_p0.read().is_01() || !bound_fu_509_p1.read().is_01())? sc_lv<64>(): sc_biguint<32>(bound_fu_509_p0.read()) * sc_biguint<32>(bound_fu_509_p1.read());
}

void OFM_STORE::thread_brmerge5_fu_998_p2() {
    brmerge5_fu_998_p2 = (newsignbit_1_fu_966_p3.read() | isneg_1_not_fu_992_p2.read());
}

void OFM_STORE::thread_brmerge_fu_891_p2() {
    brmerge_fu_891_p2 = (newsignbit_fu_859_p3.read() | isneg_not_fu_885_p2.read());
}

void OFM_STORE::thread_brmerge_i_i1_fu_879_p2() {
    brmerge_i_i1_fu_879_p2 = (isneg_fu_845_p3.read() ^ newsignbit_fu_859_p3.read());
}

void OFM_STORE::thread_brmerge_i_i_fu_986_p2() {
    brmerge_i_i_fu_986_p2 = (isneg_1_fu_952_p3.read() ^ newsignbit_1_fu_966_p3.read());
}

void OFM_STORE::thread_exitcond1_fu_467_p2() {
    exitcond1_fu_467_p2 = (!i_reg_368.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_368.read() == ap_const_lv4_8);
}

void OFM_STORE::thread_exitcond_flatten1_fu_552_p2() {
    exitcond_flatten1_fu_552_p2 = (!indvar_flatten1_reg_379.read().is_01() || !tmp_3_reg_1166.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten1_reg_379.read() == tmp_3_reg_1166.read());
}

void OFM_STORE::thread_exitcond_flatten2_fu_1050_p2() {
    exitcond_flatten2_fu_1050_p2 = (!indvar_flatten2_reg_434.read().is_01() || !bound_reg_1160.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten2_reg_434.read() == bound_reg_1160.read());
}

void OFM_STORE::thread_exitcond_flatten_fu_569_p2() {
    exitcond_flatten_fu_569_p2 = (!indvar_flatten_reg_401.read().is_01() || !bound_reg_1160.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_401.read() == bound_reg_1160.read());
}

void OFM_STORE::thread_grp_fu_1108_p0() {
    grp_fu_1108_p0 =  (sc_lv<5>) (ap_const_lv9_D);
}

void OFM_STORE::thread_grp_fu_1108_p1() {
    grp_fu_1108_p1 = (!tmp_11_mid1_fu_684_p3.read()[0].is_01())? sc_lv<9>(): ((tmp_11_mid1_fu_684_p3.read()[0].to_bool())? tmp_13_fu_713_p3.read(): tmp_22_fu_721_p1.read());
}

void OFM_STORE::thread_grp_fu_1108_p2() {
    grp_fu_1108_p2 = k_mid2_fu_697_p3.read().range(9-1, 0);
}

void OFM_STORE::thread_grp_fu_1117_p0() {
    grp_fu_1117_p0 =  (sc_lv<5>) (ap_const_lv9_D);
}

void OFM_STORE::thread_grp_fu_1117_p1() {
    grp_fu_1117_p1 = tmp_7_mid2_v_fu_1075_p3.read().range(9-1, 0);
}

void OFM_STORE::thread_grp_fu_1117_p2() {
    grp_fu_1117_p2 = k3_mid2_fu_1067_p3.read().range(9-1, 0);
}

void OFM_STORE::thread_i_1_fu_473_p2() {
    i_1_fu_473_p2 = (!i_reg_368.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_368.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void OFM_STORE::thread_i_2_fu_563_p2() {
    i_2_fu_563_p2 = (!ap_const_lv3_1.is_01() || !ap_phi_mux_i1_phi_fu_394_p4.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ap_phi_mux_i1_phi_fu_394_p4.read()));
}

void OFM_STORE::thread_indvar_flatten_next1_fu_557_p2() {
    indvar_flatten_next1_fu_557_p2 = (!indvar_flatten1_reg_379.read().is_01() || !ap_const_lv66_1.is_01())? sc_lv<66>(): (sc_biguint<66>(indvar_flatten1_reg_379.read()) + sc_biguint<66>(ap_const_lv66_1));
}

void OFM_STORE::thread_indvar_flatten_next2_fu_1055_p2() {
    indvar_flatten_next2_fu_1055_p2 = (!indvar_flatten2_reg_434.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(indvar_flatten2_reg_434.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void OFM_STORE::thread_indvar_flatten_next_fu_802_p3() {
    indvar_flatten_next_fu_802_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? ap_const_lv64_1: indvar_flatten_op_fu_796_p2.read());
}

void OFM_STORE::thread_indvar_flatten_op_fu_796_p2() {
    indvar_flatten_op_fu_796_p2 = (!ap_const_lv64_1.is_01() || !indvar_flatten_reg_401.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(indvar_flatten_reg_401.read()));
}

void OFM_STORE::thread_input_dma_B_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()))) {
        input_dma_B_TDATA_blk_n = input_dma_B_TVALID.read();
    } else {
        input_dma_B_TDATA_blk_n = ap_const_logic_1;
    }
}

void OFM_STORE::thread_input_dma_B_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read())))) {
        input_dma_B_TREADY = ap_const_logic_1;
    } else {
        input_dma_B_TREADY = ap_const_logic_0;
    }
}

void OFM_STORE::thread_isneg_1_fu_952_p3() {
    isneg_1_fu_952_p3 = p_Val2_5_fu_946_p2.read().range(26, 26);
}

void OFM_STORE::thread_isneg_1_not_fu_992_p2() {
    isneg_1_not_fu_992_p2 = (isneg_1_fu_952_p3.read() ^ ap_const_lv1_1);
}

void OFM_STORE::thread_isneg_fu_845_p3() {
    isneg_fu_845_p3 = p_Val2_2_fu_839_p2.read().range(26, 26);
}

void OFM_STORE::thread_isneg_not_fu_885_p2() {
    isneg_not_fu_885_p2 = (isneg_fu_845_p3.read() ^ ap_const_lv1_1);
}

void OFM_STORE::thread_j_1_fu_1061_p2() {
    j_1_fu_1061_p2 = (!ap_const_lv31_1.is_01() || !j2_reg_445.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(j2_reg_445.read()));
}

void OFM_STORE::thread_j_2_fu_691_p2() {
    j_2_fu_691_p2 = (!ap_const_lv31_1.is_01() || !j_mid_fu_574_p3.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(j_mid_fu_574_p3.read()));
}

void OFM_STORE::thread_j_mid2_fu_750_p3() {
    j_mid2_fu_750_p3 = (!tmp_11_mid1_fu_684_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_11_mid1_fu_684_p3.read()[0].to_bool())? j_mid_fu_574_p3.read(): j_2_fu_691_p2.read());
}

void OFM_STORE::thread_j_mid_fu_574_p3() {
    j_mid_fu_574_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? ap_const_lv31_0: j_reg_412.read());
}

void OFM_STORE::thread_k3_cast_fu_1041_p1() {
    k3_cast_fu_1041_p1 = esl_zext<32,31>(k3_reg_456.read());
}

void OFM_STORE::thread_k3_mid2_fu_1067_p3() {
    k3_mid2_fu_1067_p3 = (!tmp_9_fu_1045_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_9_fu_1045_p2.read()[0].to_bool())? k3_reg_456.read(): ap_const_lv31_0);
}

void OFM_STORE::thread_k_1_fu_1102_p2() {
    k_1_fu_1102_p2 = (!ap_const_lv31_1.is_01() || !k3_mid2_fu_1067_p3.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(k3_mid2_fu_1067_p3.read()));
}

void OFM_STORE::thread_k_2_fu_790_p2() {
    k_2_fu_790_p2 = (!ap_const_lv31_1.is_01() || !k_mid2_fu_697_p3.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(k_mid2_fu_697_p3.read()));
}

void OFM_STORE::thread_k_cast_fu_543_p1() {
    k_cast_fu_543_p1 = esl_zext<32,31>(k_reg_423.read());
}

void OFM_STORE::thread_k_cast_mid2_cast_fu_746_p1() {
    k_cast_mid2_cast_fu_746_p1 = esl_zext<32,31>(k_mid2_fu_697_p3.read());
}

void OFM_STORE::thread_k_mid2_fu_697_p3() {
    k_mid2_fu_697_p3 = (!tmp_11_mid1_fu_684_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_11_mid1_fu_684_p3.read()[0].to_bool())? k_mid_fu_582_p3.read(): ap_const_lv31_0);
}

void OFM_STORE::thread_k_mid_fu_582_p3() {
    k_mid_fu_582_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? ap_const_lv31_0: k_reg_423.read());
}

void OFM_STORE::thread_newsignbit_1_fu_966_p3() {
    newsignbit_1_fu_966_p3 = p_Val2_6_fu_960_p2.read().range(25, 25);
}

void OFM_STORE::thread_newsignbit_fu_859_p3() {
    newsignbit_fu_859_p3 = p_Val2_3_fu_853_p2.read().range(25, 25);
}

void OFM_STORE::thread_notlhs_fu_609_p2() {
    notlhs_fu_609_p2 = (!ap_phi_mux_i1_phi_fu_394_p4.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_phi_fu_394_p4.read() == ap_const_lv3_3);
}

void OFM_STORE::thread_notlhs_mid1_fu_603_p2() {
    notlhs_mid1_fu_603_p2 = (!i_2_fu_563_p2.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(i_2_fu_563_p2.read() == ap_const_lv3_3);
}

void OFM_STORE::thread_notlhs_mid2_fu_615_p3() {
    notlhs_mid2_fu_615_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? notlhs_mid1_fu_603_p2.read(): notlhs_fu_609_p2.read());
}

void OFM_STORE::thread_notrhs_fu_538_p2() {
    notrhs_fu_538_p2 = (!tmp_4_fu_534_p1.read().is_01() || !tmp_reg_1149.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_534_p1.read() == tmp_reg_1149.read());
}

void OFM_STORE::thread_notrhs_mid1_fu_733_p2() {
    notrhs_mid1_fu_733_p2 = (!p_mid1_fu_705_p1.read().is_01() || !tmp_reg_1149.read().is_01())? sc_lv<1>(): sc_lv<1>(p_mid1_fu_705_p1.read() == tmp_reg_1149.read());
}

void OFM_STORE::thread_notrhs_mid2_fu_738_p3() {
    notrhs_mid2_fu_738_p3 = (!tmp_11_mid1_fu_684_p3.read()[0].is_01())? sc_lv<1>(): ((tmp_11_mid1_fu_684_p3.read()[0].to_bool())? notrhs_mid3_fu_677_p3.read(): notrhs_mid1_fu_733_p2.read());
}

void OFM_STORE::thread_notrhs_mid3_fu_677_p3() {
    notrhs_mid3_fu_677_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? notrhs_mid_reg_1171.read(): notrhs_fu_538_p2.read());
}

void OFM_STORE::thread_notrhs_mid_fu_523_p2() {
    notrhs_mid_fu_523_p2 = (!tmp_fu_493_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_493_p2.read() == ap_const_lv32_0);
}

void OFM_STORE::thread_output_dma_O_TDATA() {
    output_dma_O_TDATA = esl_sext<56,52>(tmp_data_fu_1028_p3.read());
}

void OFM_STORE::thread_output_dma_O_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0))) {
        output_dma_O_TDATA_blk_n = output_dma_O_TREADY.read();
    } else {
        output_dma_O_TDATA_blk_n = ap_const_logic_1;
    }
}

void OFM_STORE::thread_output_dma_O_TLAST() {
    output_dma_O_TLAST =  (sc_logic) (tmp_last_reg_1218.read()[0]);
}

void OFM_STORE::thread_output_dma_O_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_1181.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_01001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_output_dma_O_TREADY.read()))) {
        output_dma_O_TVALID = ap_const_logic_1;
    } else {
        output_dma_O_TVALID = ap_const_logic_0;
    }
}

void OFM_STORE::thread_p_Val2_2_fu_839_p2() {
    p_Val2_2_fu_839_p2 = (!tmp_14_fu_831_p1.read().is_01() || !tmp_15_fu_835_p1.read().is_01())? sc_lv<27>(): (sc_bigint<27>(tmp_14_fu_831_p1.read()) + sc_bigint<27>(tmp_15_fu_835_p1.read()));
}

void OFM_STORE::thread_p_Val2_3_45_fu_905_p3() {
    p_Val2_3_45_fu_905_p3 = (!underflow_fu_873_p2.read()[0].is_01())? sc_lv<26>(): ((underflow_fu_873_p2.read()[0].to_bool())? ap_const_lv26_2000000: p_Val2_3_fu_853_p2.read());
}

void OFM_STORE::thread_p_Val2_3_fu_853_p2() {
    p_Val2_3_fu_853_p2 = (!p_Val2_s_fu_824_p3.read().is_01() || !BIAS_V_q0.read().is_01())? sc_lv<26>(): (sc_biguint<26>(p_Val2_s_fu_824_p3.read()) + sc_biguint<26>(BIAS_V_q0.read()));
}

void OFM_STORE::thread_p_Val2_3_mux_fu_897_p3() {
    p_Val2_3_mux_fu_897_p3 = (!brmerge_i_i1_fu_879_p2.read()[0].is_01())? sc_lv<26>(): ((brmerge_i_i1_fu_879_p2.read()[0].to_bool())? ap_const_lv26_1FFFFFF: p_Val2_3_fu_853_p2.read());
}

void OFM_STORE::thread_p_Val2_4_fu_935_p3() {
    p_Val2_4_fu_935_p3 = (!sel_tmp8_mid2_reg_1207.read()[0].is_01())? sc_lv<26>(): ((sel_tmp8_mid2_reg_1207.read()[0].to_bool())? OFM_6_V_q0.read(): sel_tmp2_fu_928_p3.read());
}

void OFM_STORE::thread_p_Val2_5_fu_946_p2() {
    p_Val2_5_fu_946_p2 = (!tmp_15_fu_835_p1.read().is_01() || !tmp_17_fu_942_p1.read().is_01())? sc_lv<27>(): (sc_bigint<27>(tmp_15_fu_835_p1.read()) + sc_bigint<27>(tmp_17_fu_942_p1.read()));
}

void OFM_STORE::thread_p_Val2_6_46_fu_1012_p3() {
    p_Val2_6_46_fu_1012_p3 = (!underflow_1_fu_980_p2.read()[0].is_01())? sc_lv<26>(): ((underflow_1_fu_980_p2.read()[0].to_bool())? ap_const_lv26_2000000: p_Val2_6_fu_960_p2.read());
}

void OFM_STORE::thread_p_Val2_6_fu_960_p2() {
    p_Val2_6_fu_960_p2 = (!p_Val2_4_fu_935_p3.read().is_01() || !BIAS_V_q0.read().is_01())? sc_lv<26>(): (sc_biguint<26>(p_Val2_4_fu_935_p3.read()) + sc_biguint<26>(BIAS_V_q0.read()));
}

void OFM_STORE::thread_p_Val2_6_mux_fu_1004_p3() {
    p_Val2_6_mux_fu_1004_p3 = (!brmerge_i_i_fu_986_p2.read()[0].is_01())? sc_lv<26>(): ((brmerge_i_i_fu_986_p2.read()[0].to_bool())? ap_const_lv26_1FFFFFF: p_Val2_6_fu_960_p2.read());
}

void OFM_STORE::thread_p_Val2_s_fu_824_p3() {
    p_Val2_s_fu_824_p3 = (!sel_tmp8_mid2_reg_1207.read()[0].is_01())? sc_lv<26>(): ((sel_tmp8_mid2_reg_1207.read()[0].to_bool())? OFM_2_V_q0.read(): sel_tmp7_fu_817_p3.read());
}

void OFM_STORE::thread_p_mid1_fu_705_p1() {
    p_mid1_fu_705_p1 = esl_zext<32,31>(j_2_fu_691_p2.read());
}

void OFM_STORE::thread_sel_tmp1_fu_921_p3() {
    sel_tmp1_fu_921_p3 = (!sel_tmp_mid2_reg_1195.read()[0].is_01())? sc_lv<26>(): ((sel_tmp_mid2_reg_1195.read()[0].to_bool())? OFM_4_V_q0.read(): OFM_7_V_q0.read());
}

void OFM_STORE::thread_sel_tmp2_fu_928_p3() {
    sel_tmp2_fu_928_p3 = (!sel_tmp6_mid2_reg_1201.read()[0].is_01())? sc_lv<26>(): ((sel_tmp6_mid2_reg_1201.read()[0].to_bool())? OFM_5_V_q0.read(): sel_tmp1_fu_921_p3.read());
}

void OFM_STORE::thread_sel_tmp3_fu_643_p2() {
    sel_tmp3_fu_643_p2 = (!ap_phi_mux_i1_phi_fu_394_p4.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_phi_fu_394_p4.read() == ap_const_lv3_1);
}

void OFM_STORE::thread_sel_tmp4_fu_663_p2() {
    sel_tmp4_fu_663_p2 = (!ap_phi_mux_i1_phi_fu_394_p4.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_phi_fu_394_p4.read() == ap_const_lv3_2);
}

void OFM_STORE::thread_sel_tmp5_fu_810_p3() {
    sel_tmp5_fu_810_p3 = (!sel_tmp_mid2_reg_1195.read()[0].is_01())? sc_lv<26>(): ((sel_tmp_mid2_reg_1195.read()[0].to_bool())? OFM_0_V_q0.read(): OFM_3_V_q0.read());
}

void OFM_STORE::thread_sel_tmp6_mid2_fu_649_p3() {
    sel_tmp6_mid2_fu_649_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? sel_tmp_fu_629_p2.read(): sel_tmp3_fu_643_p2.read());
}

void OFM_STORE::thread_sel_tmp7_fu_817_p3() {
    sel_tmp7_fu_817_p3 = (!sel_tmp6_mid2_reg_1201.read()[0].is_01())? sc_lv<26>(): ((sel_tmp6_mid2_reg_1201.read()[0].to_bool())? OFM_1_V_q0.read(): sel_tmp5_fu_810_p3.read());
}

void OFM_STORE::thread_sel_tmp8_mid1_fu_657_p2() {
    sel_tmp8_mid1_fu_657_p2 = (!i_2_fu_563_p2.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(i_2_fu_563_p2.read() == ap_const_lv3_2);
}

void OFM_STORE::thread_sel_tmp8_mid2_fu_669_p3() {
    sel_tmp8_mid2_fu_669_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? sel_tmp8_mid1_fu_657_p2.read(): sel_tmp4_fu_663_p2.read());
}

void OFM_STORE::thread_sel_tmp_fu_629_p2() {
    sel_tmp_fu_629_p2 = (!ap_phi_mux_i1_phi_fu_394_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_phi_fu_394_p4.read() == ap_const_lv3_0);
}

void OFM_STORE::thread_sel_tmp_mid1_fu_623_p2() {
    sel_tmp_mid1_fu_623_p2 = (!i_2_fu_563_p2.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(i_2_fu_563_p2.read() == ap_const_lv3_0);
}

void OFM_STORE::thread_sel_tmp_mid2_fu_635_p3() {
    sel_tmp_mid2_fu_635_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? sel_tmp_mid1_fu_623_p2.read(): sel_tmp_fu_629_p2.read());
}

void OFM_STORE::thread_tmp6_fu_763_p2() {
    tmp6_fu_763_p2 = (notlhs_mid2_fu_615_p3.read() & tmp_5_fu_758_p2.read());
}

void OFM_STORE::thread_tmp_11_fu_709_p1() {
    tmp_11_fu_709_p1 = j_reg_412.read().range(9-1, 0);
}

void OFM_STORE::thread_tmp_11_mid1_fu_684_p3() {
    tmp_11_mid1_fu_684_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? tmp_11_mid_reg_1176.read(): tmp_6_fu_547_p2.read());
}

void OFM_STORE::thread_tmp_11_mid_fu_529_p2() {
    tmp_11_mid_fu_529_p2 = (!custom_Tc.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(custom_Tc.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void OFM_STORE::thread_tmp_13_fu_713_p3() {
    tmp_13_fu_713_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<9>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? ap_const_lv9_0: tmp_11_fu_709_p1.read());
}

void OFM_STORE::thread_tmp_14_cast_fu_779_p1() {
    tmp_14_cast_fu_779_p1 = esl_sext<64,9>(grp_fu_1108_p3.read());
}

void OFM_STORE::thread_tmp_14_fu_831_p1() {
    tmp_14_fu_831_p1 = esl_sext<27,26>(p_Val2_s_fu_824_p3.read());
}

void OFM_STORE::thread_tmp_15_fu_835_p1() {
    tmp_15_fu_835_p1 = esl_sext<27,26>(BIAS_V_q0.read());
}

void OFM_STORE::thread_tmp_16_fu_867_p2() {
    tmp_16_fu_867_p2 = (newsignbit_fu_859_p3.read() ^ ap_const_lv1_1);
}

void OFM_STORE::thread_tmp_17_fu_942_p1() {
    tmp_17_fu_942_p1 = esl_sext<27,26>(p_Val2_4_fu_935_p3.read());
}

void OFM_STORE::thread_tmp_18_fu_974_p2() {
    tmp_18_fu_974_p2 = (newsignbit_1_fu_966_p3.read() ^ ap_const_lv1_1);
}

void OFM_STORE::thread_tmp_21_cast_fu_1091_p1() {
    tmp_21_cast_fu_1091_p1 = esl_sext<64,9>(grp_fu_1117_p3.read());
}

void OFM_STORE::thread_tmp_22_fu_721_p1() {
    tmp_22_fu_721_p1 = j_2_fu_691_p2.read().range(9-1, 0);
}

void OFM_STORE::thread_tmp_2_fu_488_p1() {
    tmp_2_fu_488_p1 = esl_zext<64,4>(i_reg_368.read());
}

void OFM_STORE::thread_tmp_3_fu_515_p3() {
    tmp_3_fu_515_p3 = esl_concat<64,2>(bound_fu_509_p2.read(), ap_const_lv2_0);
}

void OFM_STORE::thread_tmp_4_fu_534_p1() {
    tmp_4_fu_534_p1 = esl_zext<32,31>(j_reg_412.read());
}

void OFM_STORE::thread_tmp_4_mid2_fu_598_p1() {
    tmp_4_mid2_fu_598_p1 = esl_zext<64,3>(tmp_4_mid2_v_fu_590_p3.read());
}

void OFM_STORE::thread_tmp_4_mid2_v_fu_590_p3() {
    tmp_4_mid2_v_fu_590_p3 = (!exitcond_flatten_fu_569_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_flatten_fu_569_p2.read()[0].to_bool())? i_2_fu_563_p2.read(): ap_phi_mux_i1_phi_fu_394_p4.read());
}

void OFM_STORE::thread_tmp_5_fu_758_p2() {
    tmp_5_fu_758_p2 = (!k_cast_mid2_cast_fu_746_p1.read().is_01() || !tmp_s_reg_1155.read().is_01())? sc_lv<1>(): sc_lv<1>(k_cast_mid2_cast_fu_746_p1.read() == tmp_s_reg_1155.read());
}

void OFM_STORE::thread_tmp_6_fu_547_p2() {
    tmp_6_fu_547_p2 = (!k_cast_fu_543_p1.read().is_01() || !custom_Tc.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_cast_fu_543_p1.read()) < sc_bigint<32>(custom_Tc.read()));
}

void OFM_STORE::thread_tmp_7_mid2_v_fu_1075_p3() {
    tmp_7_mid2_v_fu_1075_p3 = (!tmp_9_fu_1045_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_9_fu_1045_p2.read()[0].to_bool())? j2_reg_445.read(): j_1_fu_1061_p2.read());
}

void OFM_STORE::thread_tmp_9_fu_1045_p2() {
    tmp_9_fu_1045_p2 = (!k3_cast_fu_1041_p1.read().is_01() || !custom_Tc.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k3_cast_fu_1041_p1.read()) < sc_bigint<32>(custom_Tc.read()));
}

void OFM_STORE::thread_tmp_data_data1_V_fu_913_p3() {
    tmp_data_data1_V_fu_913_p3 = (!brmerge_fu_891_p2.read()[0].is_01())? sc_lv<26>(): ((brmerge_fu_891_p2.read()[0].to_bool())? p_Val2_3_mux_fu_897_p3.read(): p_Val2_3_45_fu_905_p3.read());
}

void OFM_STORE::thread_tmp_data_data2_V_fu_1020_p3() {
    tmp_data_data2_V_fu_1020_p3 = (!brmerge5_fu_998_p2.read()[0].is_01())? sc_lv<26>(): ((brmerge5_fu_998_p2.read()[0].to_bool())? p_Val2_6_mux_fu_1004_p3.read(): p_Val2_6_46_fu_1012_p3.read());
}

void OFM_STORE::thread_tmp_data_fu_1028_p3() {
    tmp_data_fu_1028_p3 = esl_concat<26,26>(tmp_data_data2_V_fu_1020_p3.read(), tmp_data_data1_V_fu_913_p3.read());
}

void OFM_STORE::thread_tmp_fu_493_p2() {
    tmp_fu_493_p2 = (!custom_Tr.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(custom_Tr.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void OFM_STORE::thread_tmp_last_fu_769_p2() {
    tmp_last_fu_769_p2 = (tmp6_fu_763_p2.read() & notrhs_mid2_fu_738_p3.read());
}

void OFM_STORE::thread_tmp_s_fu_498_p2() {
    tmp_s_fu_498_p2 = (!custom_Tc.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(custom_Tc.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void OFM_STORE::thread_underflow_1_fu_980_p2() {
    underflow_1_fu_980_p2 = (isneg_1_fu_952_p3.read() & tmp_18_fu_974_p2.read());
}

void OFM_STORE::thread_underflow_fu_873_p2() {
    underflow_fu_873_p2 = (isneg_fu_845_p3.read() & tmp_16_fu_867_p2.read());
}

void OFM_STORE::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_467_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, input_dma_B_TVALID.read())) && esl_seteq<1,1,1>(exitcond1_fu_467_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_fu_552_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_fu_552_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_1050_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

